
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2025

import System
import Darwin

/// A forward Unicode parser that maps each byte directly to a Latin-1 scalar.
///
/// Used as the `ForwardParser` associated type of ``ISOLatin1``.
public struct ForwardParserX : Unicode.Parser {
  /// Creates a new forward parser.
  public init() {}

  /// Reads the next byte from `input` and wraps it in a single-element collection.
  ///
  /// - Parameter input: An iterator over `UInt8` bytes.
  /// - Returns: `.valid` with the next byte, or `.emptyInput` when the iterator is exhausted.
  public mutating func parseScalar<I>(from input: inout I) -> Unicode.ParseResult<CollectionOfOne<UInt8>> where I : IteratorProtocol, I.Element == UInt8 {
    if let z = input.next() {
      let x = CollectionOfOne(UInt8(z) )
      return Unicode.ParseResult.valid(x)
    } else {
      return Unicode.ParseResult.emptyInput
    }
  }
  
  /// The encoding this parser serves.
  public typealias Encoding = ISOLatin1
}

/// A reverse Unicode parser that maps each byte directly to a Latin-1 scalar.
///
/// Used as the `ReverseParser` associated type of ``ISOLatin1``.
public struct ReverseParserX : Unicode.Parser {
  /// Creates a new reverse parser.
  public init() {}

  /// Reads the next byte from `input` and wraps it in a single-element collection.
  ///
  /// - Parameter input: An iterator over `UInt8` bytes.
  /// - Returns: `.valid` with the next byte, or `.emptyInput` when the iterator is exhausted.
  public mutating func parseScalar<I>(from input: inout I) -> Unicode.ParseResult<CollectionOfOne<UInt8>> where I : IteratorProtocol, I.Element == UInt8 {
    if let z = input.next() {
      let x = CollectionOfOne(UInt8(z) )
      return Unicode.ParseResult.valid(x)
    } else {
      return Unicode.ParseResult.emptyInput
    }
  }
  
  /// The encoding this parser serves.
  public typealias Encoding = ISOLatin1
}

/// A `Unicode.Encoding` implementation for ISO Latin-1 (ISO 8859-1).
///
/// Each code unit is a single byte, and each byte value maps directly to the
/// corresponding Unicode scalar (U+0000–U+00FF).
public struct ISOLatin1: Unicode.Encoding {
  /// The replacement character used when encoding fails (U+0000).
  public static let encodedReplacementCharacter: CollectionOfOne<UInt8> = .init(UInt8(0))
  
  /// Decodes a single ISO Latin-1 code unit into a Unicode scalar.
  ///
  /// - Parameter content: A one-element collection holding the byte to decode.
  /// - Returns: The Unicode scalar whose value equals the byte value.
  public static func decode(_ content: CollectionOfOne<UInt8>) -> Unicode.Scalar {
    return Unicode.Scalar(content.first!)
  }
  
  /// Encodes a Unicode scalar into a single ISO Latin-1 byte.
  ///
  /// - Parameter content: A Unicode scalar with a value in the range 0–255.
  /// - Returns: A one-element collection holding the encoded byte, or `nil` if
  ///   the scalar's value exceeds 255.
  public static func encode(_ content: Unicode.Scalar) -> CollectionOfOne<UInt8>? {
    return CollectionOfOne( UInt8(content.value) )
  }
  
  /// The code-unit type: a single byte.
  public typealias CodeUnit = UInt8
  /// The encoded-scalar type: a one-element byte collection.
  public typealias EncodedScalar = CollectionOfOne<UInt8>
  /// The forward parser type.
  public typealias ForwardParser = ForwardParserX
  /// The reverse parser type.
  public typealias ReverseParser = ReverseParserX
}

/// Errors thrown when a Unicode scalar cannot be represented in ISO Latin-1.
enum Latin1EncodingError: Error {
  /// The scalar's value is greater than 255.
  case scalarOutOfRange(UnicodeScalar)
}

// get bytes from String encoded as ISOLatin1
public extension String {
  /// Encodes the string as ISO Latin-1 bytes.
  ///
  /// - Returns: A `[UInt8]` array where each byte corresponds to the Unicode scalar
  ///   value of the character at that position.
  /// - Throws: ``Latin1EncodingError/scalarOutOfRange(_:)`` if any scalar has a value
  ///   greater than 255.
  func isoLatin1() throws -> [UInt8] {
    var result: [UInt8] = []
    result.reserveCapacity(self.unicodeScalars.count)

    for scalar in self.unicodeScalars {
      let v = scalar.value
      guard v <= 0xFF else {
        throw Latin1EncodingError.scalarOutOfRange(scalar)
      }
      result.append(UInt8(v))
    }

    return result
  }
}

/// Returns a human-readable error message for a POSIX regex error code.
///
/// - Parameters:
///   - n: The error code returned by a `reg*` function.
///   - regx: The compiled regular expression that produced the error.
/// - Returns: A string describing the error.
public func regerror(_ n : Int32, _ regx : Darwin.regex_t )  -> String {
  var re = regx
  let s = withUnsafeMutablePointer(to: &re) { rr in
     regerror(n, rr, nil, 0)
  }
  
  let p = withUnsafeTemporaryAllocation(of: UInt8.self, capacity: s) { b in
    withUnsafeMutablePointer(to: &re) {rr in
      let _ = regerror(n, rr, b.baseAddress!, s)
      return String(cString: b.baseAddress!)
    }
  }
  return p
}

/// Formats a string using a C-style `printf` format and a variadic argument list.
///
/// The output is decoded as ISO Latin-1 to preserve non-ASCII byte values.
///
/// - Parameters:
///   - format: A `printf`-style format string.
///   - args: Zero or more `CVarArg` values matching the format specifiers.
/// - Returns: The formatted string.
public func cFormat(_ format: String, _ args: CVarArg...) -> String {
    let bufferSize = 1024
    var buffer = [UInt8](repeating: 0, count: bufferSize)

  return buffer.withUnsafeMutableBufferPointer { ptr in
    let n = withVaList(args) { vaPtr in
      vsnprintf(ptr.baseAddress!, bufferSize, format, vaPtr)
    }
    let pp = UnsafeBufferPointer(start: ptr.baseAddress!, count: Int(n) )
    return String(decoding: pp, as: ISOLatin1.self)
  }
}

/// Formats a single string argument using a C-style `printf` format.
///
/// This overload avoids the overhead of a variadic `va_list` when exactly one
/// `String` argument is needed.
///
/// - Parameters:
///   - format: A `printf`-style format string with a single `%s` specifier.
///   - args: The string argument.
/// - Returns: The formatted string.
public func cFormat(_ format: String, _ args: String) -> String {
  return args.withCString { c in cFormat(format, c) }
}

extension Substring {
  /// Returns a copy of the substring with leading and trailing characters from `shouldTrim` removed.
  ///
  /// - Parameter shouldTrim: The set of characters to strip from both ends.
  /// - Returns: A sub-slice with the specified characters trimmed.
  public func trimming(_ shouldTrim: [Character]) -> Substring {
    var start = startIndex
    var end = endIndex

    while start < end && shouldTrim.contains(self[start]) {
      formIndex(after: &start)
    }

    while end > start && shouldTrim.contains(self[index(before: end)]) {
      formIndex(before: &end)
    }

    return self[start..<end]
  }
}

extension StringProtocol {
  /// Returns the total display width of the string, in terminal column units.
  ///
  /// Sums the ``wcwidth`` of each `Character`.  Control characters (which have a
  /// `wcwidth` of -1) are treated as zero-width.
  ///
  /// - Returns: The number of terminal columns required to display the string.
  public func wcwidth() -> Int {
    return self.reduce(0) { (sum : Int, scal : Character) in
      let t = scal.wcwidth
      if t > 0 { return sum + Int(t) }
      else { return sum }
    }
  }
}

extension Character {

  /// `true` if the character has emoji presentation (contains at least one scalar
  /// with `isEmojiPresentation` or `isEmoji` set).
  public var isEmoji : Bool {
    return self.unicodeScalars.contains { scalar in
      scalar.properties.isEmojiPresentation || scalar.properties.isEmoji
    }
  }

  /// Returns the display width of the character in terminal columns.
  ///
  /// Returns `-1` if the character contains any control characters (values below
  /// U+0020 or in the range U+007F–U+009F).  Emoji that are at least two columns
  /// wide are normalised to exactly 2.
  public var wcwidth : Int {
    for scalar in self.unicodeScalars {
      let v = scalar.value
      if (v < 0x20) || (v >= 0x7F && v < 0xA0) {
        return -1
      }
    }

    var width = 0
    for scalar in self.unicodeScalars {
      width += scalar.wcwidth
    }

    if self.isEmoji && width >= 2 {
      return 2
    }

    return width
  }

  /// Returns `true` if the character is printable and not a space.
  ///
  /// Equivalent to POSIX `iswgraph`.  Returns `false` for control characters,
  /// format characters, surrogates, private-use code points, unassigned code
  /// points, and any category of separator.
  public var iswgraph : Bool {
    for scalar in self.unicodeScalars {
      switch scalar.properties.generalCategory {
      case .control, .format, .surrogate, .privateUse, .unassigned,
           .spaceSeparator, .lineSeparator, .paragraphSeparator:
        return false
      default:
        continue
      }
    }

    if self.isWhitespace {
      return false
    }

    return true
  }

  /// Returns `true` if the character is printable (including spaces).
  ///
  /// Equivalent to POSIX `iswprint`.  For ASCII, only U+0020–U+007E are considered
  /// printable.  For non-ASCII, characters in the Latin Supplement block
  /// (U+0080–U+00FF) are not printable; all others that are not control, format,
  /// surrogate, private-use, or unassigned are considered printable.
  public var iswprint : Bool {
    let scalars = self.unicodeScalars
    if scalars.count > 1 { return true }
    let scalar = scalars.first!
    if scalar.isASCII {
      return scalar.value >= 0x20 && scalar.value <= 0x7E
    } else {
      if scalar.value < 256 { return false }
      switch scalar.properties.generalCategory {
      case .control, .format, .surrogate, .privateUse, .unassigned:
        return false
      default:
        return true
      }
    }
  }
}

extension UnicodeScalar {

  /// Returns the terminal display width of the scalar in columns.
  ///
  /// Combining marks return 0; emoji-presentation scalars and East Asian Wide
  /// characters return 2; all other scalars return 1.
  public var wcwidth : Int {
    switch self.properties.generalCategory {
      case .nonspacingMark, .enclosingMark:
        return 0
      default:
        break
    }

    if self.properties.isEmojiPresentation {
      return 2
    }

    let wideRanges: [ClosedRange<UInt32>] = [
      0x1100...0x115F, 0x2329...0x232A, 0x2E80...0xA4CF, 0xAC00...0xD7A3,
      0xF900...0xFAFF, 0xFE10...0xFE19, 0xFE30...0xFE6F, 0xFF00...0xFF60,
      0xFFE0...0xFFE6, 0x1F300...0x1F64F, 0x1F900...0x1F9FF, 0x20000...0x3FFFD
    ]
    if wideRanges.contains(where: { $0.contains(self.value) }) {
      return 2
    }

    return 1
  }

  /// Returns `true` if the scalar is a printable, non-space character.
  ///
  /// Equivalent to POSIX `iswgraph` applied to a single scalar.
  public var iswgraph : Bool {
    if self.isASCII {
      return (0x21...0x7E).contains(self.value)
    } else {
      switch self.properties.generalCategory {
      case .control, .format, .surrogate, .privateUse, .unassigned,
           .spaceSeparator, .lineSeparator, .paragraphSeparator:
        return false
      default:
        return true
      }
    }
  }
}

/// Decodes a UTF-16 buffer into a Swift `String`, returning `nil` if the buffer
/// contains invalid UTF-16 code units.
///
/// - Parameter buffer: A `[UInt16]` array of UTF-16 code units.
/// - Returns: The decoded `String`, or `nil` if invalid UTF-16 is encountered.
public func validatedStringFromUTF16Buffer(_ buffer: [UInt16]) -> String? {
  var decoder = UTF16()
  var iterator = buffer.makeIterator()
  var string = ""

  decodeLoop: while true {
    switch decoder.decode(&iterator) {
    case .scalarValue(let scalar):
      string.unicodeScalars.append(scalar)
    case .emptyInput:
      break decodeLoop
    case .error:
      return nil
    }
  }

  return string
}

/// Returns the index of the first invalid UTF-8 byte sequence in the given byte array,
/// or `nil` if all bytes form valid UTF-8.
///
/// - Parameter bytes: The byte array to validate.
/// - Returns: The zero-based index of the first invalid byte, or `nil` if the
///   entire array is valid UTF-8.
func firstInvalidUTF8Index(in bytes: [UInt8]) -> Int? {
  var decoder = UTF8()
  var iterator = bytes.makeIterator()
  var index = 0

  while true {
    let decoding = decoder.decode(&iterator)
    switch decoding {
    case .scalarValue:
      index += 1
    case .emptyInput:
      return nil
    case .error:
      return index
    }
  }
}

/// Returns the `Unicode.Encoding` type that corresponds to the current locale's character set.
///
/// Uses `nl_langinfo(CODESET)` to determine the encoding name.  Returns `nil` for
/// any encoding that is not explicitly handled.
///
/// - Returns: A `Unicode.Encoding.Type` for `UTF-8`, `ISO-8859-1`, or `UTF-16`;
///   `nil` for all other codeset names.
func getStringEncoding() -> (any Unicode.Encoding.Type)? {
  let codeset = String(cString: nl_langinfo(CODESET))
  switch codeset.uppercased() {
  case "UTF-8":
    return UTF8.self
  case "ISO-8859-1", "LATIN1":
    return ISOLatin1.self
  case "UTF-16":
    return UTF16.self
  default:
    return nil
  }
}
