// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2025

import Darwin

public struct FileSystemFlags : OptionSet, Sendable {
  public var rawValue : UInt32

  public init(rawValue: UInt32) {
    self.rawValue = rawValue
  }

  public static let RDONLY      = Self.init(rawValue: 0x00000001)
  public static let SYNCHRONOUS = Self.init(rawValue: 0x00000002)
  public static let NOEXEC      = Self.init(rawValue: 0x00000004)
  public static let NOSUID      = Self.init(rawValue: 0x00000008)
  public static let NODEV       = Self.init(rawValue: 0x00000010)
  public static let UNION       = Self.init(rawValue: 0x00000020)
  public static let ASYNC       = Self.init(rawValue: 0x00000040)
  public static let CPROTECT    = Self.init(rawValue: 0x00000080)
  public static let EXPORTED    = Self.init(rawValue: 0x00000100)
  public static let REMOVABLE   = Self.init(rawValue: 0x00000200)
  public static let QUARANTINE  = Self.init(rawValue: 0x00000400)

  public static let LOCAL       = Self.init(rawValue: 0x00001000)
  public static let QUOTA       = Self.init(rawValue: 0x00002000)
  public static let ROOTFS      = Self.init(rawValue: 0x00004000)
  public static let DOVOLFS     = Self.init(rawValue: 0x00008000)
  public static let DONTBROWSE  = Self.init(rawValue: 0x00100000)
  public static let IGNORE_OWNERSHIP = Self.init(rawValue: 0x00200000)
  public static let AUTOMOUNTED = Self.init(rawValue: 0x00400000)
  public static let JOURNALED   = Self.init(rawValue: 0x00800000)
  public static let NOUSERXATTR = Self.init(rawValue: 0x01000000)
  public static let DEFWRITE    = Self.init(rawValue: 0x02000000)
  public static let MULTILABEL  = Self.init(rawValue: 0x04000000)
  public static let NOFOLLOW    = Self.init(rawValue: 0x08000000)
  public static let NOATIME     = Self.init(rawValue: 0x10000000)

  public static let SNAPSHOT    = Self.init(rawValue: 0x40000000)
  public static let STRICTATIME = Self.init(rawValue: 0x80000000)
}

public struct FileSystemMetadata {
  public var bsize : UInt        /* fundamental file system block size */
  public var iosize : UInt       /* optimal transfer block size */
  public var blocks : UInt       /* total data blocks in file system */
  public var bfree : UInt        /* free blocks in fs */
  public var bavail : UInt       /* free blocks avail to non-superuser */
  public var files : UInt        /* total file nodes in file system */
  public var ffree : UInt        /* free file nodes in fs */
  public var fsid : (UInt32, UInt32)  /* file system id */
  public var owner : UInt        /* user that mounted the filesystem */
  public var type : UInt         /* type of filesystem */
  public var flags : FileSystemFlags   /* copy of mount exported flags */
  public var fssubtype : UInt    /* fs sub-type (flavor) */
  public var fstypename : String
  public var mntonname : String
  public var mntfromname : String

  public init(for x: String) throws(POSIXErrno) {
    var sfs = statfs()
    let e = statfs(x, &sfs)
    try self.init(e, sfs)
  }

  public init(for x : FileDescriptor) throws(POSIXErrno) {
    var sfs = statfs()
    let e = fstatfs(x.rawValue, &sfs)
    try self.init(e, sfs)
  }

  private init(_ e : Int32, _ sfs : statfs) throws(POSIXErrno) {
    if (e != 0) { throw POSIXErrno(e) }
    bsize = UInt(sfs.f_bsize)
    iosize = UInt(sfs.f_iosize)
    blocks = UInt(sfs.f_blocks)
    bfree = UInt(sfs.f_bfree)
    bavail = UInt(sfs.f_bavail)
    files = UInt(sfs.f_files)
    ffree = UInt(sfs.f_ffree)
    fsid = (UInt32(sfs.f_fsid.val.0), UInt32(sfs.f_fsid.val.1))
    owner = UInt(sfs.f_owner)
    type = UInt(sfs.f_type)
    flags = FileSystemFlags(rawValue: sfs.f_flags)
    fssubtype = UInt(sfs.f_fssubtype)


    fstypename = withUnsafeBytes(of: sfs.f_fstypename) {jj in
      return String(String(decoding: jj, as: UTF8.self).prefix { $0 != "\0" })
    }

    mntonname = withUnsafeBytes(of: sfs.f_mntonname) {jj in
      return String(String(decoding: jj, as: UTF8.self).prefix { $0 != "\0" })
    }

    mntfromname = withUnsafeBytes(of: sfs.f_mntfromname) {jj in
      return String(String(decoding: jj, as: UTF8.self).prefix { $0 != "\0" })
    }

  }
}

