
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2026

import System
import Darwin

/// A buffered, stdio-like I/O wrapper around a `FileDescriptor`.
///
/// `FileStream` provides:
/// - Delimiter-based buffered reads (e.g. line-at-a-time).
/// - Buffered, auto-flushing writes.
/// - No Foundation dependency — all I/O is in raw bytes.
///
/// Encoding is the caller's responsibility: bytes are passed in and out without
/// any transcoding unless you use the ``readLineUTF8(maxBytes:)`` / ``writeUTF8(_:)``
/// helpers.
public struct FileStream {
  /// Whether the `FileDescriptor` is owned (and should be closed) by this instance.
  enum Ownership { case borrowed, owned }
  /// The access direction requested when opening.
  enum Mode { case read, write, readWrite }

  /// The underlying file descriptor.
  var fd: FileDescriptor
  /// Ownership semantics of `fd`.
  let ownership: Ownership

  // Read buffering
  private var rbuf: [UInt8] = []
  private var eof = false

  // Write buffering
  private var wbuf: [UInt8] = []
  /// Byte count threshold at which buffered output is automatically flushed.
  var writeBufferLimit: Int = 64 * 1024

  /// Opens the file at `fp` for the given access mode.
  ///
  /// - Parameters:
  ///   - fp: The path to open.
  ///   - mode: The access mode. Defaults to `.readWrite`.
  /// - Throws: ``POSIXErrno`` if the file cannot be opened.
  public init(_ fp : FilePath, mode: FileDescriptor.AccessMode = .readWrite) throws(POSIXErrno) {
    do {
      self.fd = try FileDescriptor.open(fp, mode)
      self.ownership = .owned
    } catch(let e as Errno) {
      throw POSIXErrno(e.rawValue, fn: "open")
    } catch(let e) {
      throw POSIXErrno(errno == 0 ? EBADF : errno, fn: "open")
    }
  }

  /// Wraps an existing `FileDescriptor` without taking ownership.
  ///
  /// The descriptor will not be closed when this `FileStream` is destroyed.
  ///
  /// - Parameter fd: The file descriptor to wrap.
  public init(_ fd: FileDescriptor) {
    self.fd = fd
    self.ownership = .borrowed
  }

  /// Flushes any buffered output, then closes the descriptor if it is owned.
  mutating func close() throws {
    try flush()
    if ownership == .owned {
      try fd.close()
    }
  }

  // MARK: - Reading

  /// Read some bytes from the FD into the read buffer.
  /// Returns number of bytes read (0 = EOF).
  private mutating func fill(minimum: Int = 1) throws(POSIXErrno) -> Int {
    guard !eof else { return 0 }
    let (n, e) : (Int?, POSIXErrno?) = withUnsafeTemporaryAllocation(byteCount: 4096, alignment: 8) { tmp  in
      do {
        let n = try fd.read(into: tmp)
        if n == 0 { eof = true; return (0, nil) }
        rbuf.append(contentsOf: tmp[..<n])
        return (n, nil)
      } catch(let e as Errno) {
        return (nil, POSIXErrno(e.rawValue, fn: "read") )
      } catch(let e) {
        return (nil, POSIXErrno(EBADF, fn: "read", reason: "\(e)"))
      }
    }
    if let n {
      return n
    } else {
      throw e!
    }
  }

  /// Reads bytes from the stream until the given delimiter is encountered.
  ///
  /// - Parameters:
  ///   - delimiter: The byte value to search for (e.g. `0x0A` for newline).
  ///   - includeDelimiter: If `true`, the delimiter byte is included in the returned array.
  ///   - maxBytes: A safety cap on the number of buffered bytes to prevent unbounded growth.
  /// - Returns: The accumulated bytes up to (and optionally including) the delimiter,
  ///   or `nil` when EOF is reached with no pending data.
  /// - Throws: ``POSIXErrno`` with `E2BIG` if `maxBytes` is exceeded before a delimiter is found.
  public mutating func readUntil(
    _ delimiter: UInt8,
    includeDelimiter: Bool = false,
    maxBytes: Int = 8 * 1024 * 1024
  ) throws(POSIXErrno) -> [UInt8]? {
    while true {
      if let i = rbuf.firstIndex(of: delimiter) {
        let end = includeDelimiter ? rbuf.index(after: i) : i
        let out = Array(rbuf[..<end])
        rbuf.removeFirst(includeDelimiter ? (i + 1) : (i + 1))
        return out
      }

      if eof {
        if rbuf.isEmpty { return nil }
        let out = rbuf
        rbuf.removeAll(keepingCapacity: true)
        return out
      }

      if rbuf.count >= maxBytes {
        throw POSIXErrno( E2BIG, fn: "readUntil" )
      }

      _ = try fill()
    }
  }

  // ==========================================================================

  /// Reads a newline-terminated line from the stream (newline not included).
  ///
  /// Equivalent to `fgets(3)` in C.
  ///
  /// - Parameter maxBytes: Maximum line length cap to avoid unbounded buffering.
  /// - Returns: The line bytes without the trailing `'\n'`, or `nil` at EOF.
  /// - Throws: ``POSIXErrno`` if a read error occurs or the line exceeds `maxBytes`.
  public mutating func readLine(maxBytes: Int = 8 * 1024 * 1024) throws(POSIXErrno) -> [UInt8]? {
    return try readUntil(0x0A, includeDelimiter: false, maxBytes: maxBytes)
  }

  /// Reads exactly `count` bytes unless EOF is reached first.
  ///
  /// - Parameter count: The number of bytes to read.
  /// - Returns: Up to `count` bytes, or `nil` if the stream is already at EOF.
  /// - Throws: ``POSIXErrno`` with `EINVAL` if `count` is negative.
  mutating func readBytes(_ count: Int) throws(POSIXErrno) -> [UInt8]? {
    guard count >= 0 else { throw POSIXErrno(EINVAL, fn: "readBytes" ) }
    while rbuf.count < count && !eof {
      _ = try fill(minimum: count - rbuf.count)
    }
    if rbuf.isEmpty && eof { return nil }
    let n = min(count, rbuf.count)
    let out = Array(rbuf[..<n])
    rbuf.removeFirst(n)
    return out
  }

  // MARK: - Writing

  /// Appends bytes to the write buffer, flushing automatically when ``writeBufferLimit`` is reached.
  ///
  /// - Parameter bytes: The bytes to buffer for output.
  /// - Throws: ``POSIXErrno`` if a flush fails.
  public mutating func write(_ bytes: [UInt8]) throws(POSIXErrno) {
    wbuf.append(contentsOf: bytes)
    if wbuf.count >= writeBufferLimit {
      try flush()
    }
  }

  /// Appends a single byte to the write buffer, flushing automatically when ``writeBufferLimit`` is reached.
  ///
  /// - Parameter byte: The byte to buffer.
  /// - Throws: ``POSIXErrno`` if a flush fails.
  public mutating func putc(_ byte: UInt8) throws(POSIXErrno) {
    wbuf.append(byte)
    if wbuf.count >= writeBufferLimit {
      try flush()
    }
  }

  /// Writes bytes followed by a newline (`0x0A`) character.
  ///
  /// - Parameter bytes: The bytes to write before the newline.
  /// - Throws: ``POSIXErrno`` if a write or flush fails.
  public mutating func writeLine(_ bytes: [UInt8]) throws(POSIXErrno) {
    try write(bytes)
    try putc(0x0A)
  }

  /// Flushes all buffered output to the underlying file descriptor.
  ///
  /// Equivalent to `fflush(3)`.
  ///
  /// - Throws: ``POSIXErrno`` if the write fails.
  public mutating func flush() throws(POSIXErrno) {
    guard !wbuf.isEmpty else { return }
    var total = 0
    while total < wbuf.count {
      let (n, e) = wbuf.withUnsafeBytes { raw -> (Int?, POSIXErrno?) in
        let base = raw.baseAddress!.advanced(by: total)
        do {
          let n = try fd.write(UnsafeRawBufferPointer(start: base, count: wbuf.count - total))
          return (n, nil)
        } catch(let e as Errno) {
          return (nil, POSIXErrno(e.rawValue, fn: "write flush"))
        } catch(let e) {
          return (nil, POSIXErrno(EIO, fn: "write flush"))
        }
      }
      if let e {
        throw e
      }
      if n == 0 { throw POSIXErrno(EIO, fn: "write flush") }
      total += n!
    }
    wbuf.removeAll(keepingCapacity: true)
  }
}

// MARK: - Tiny helpers (no Foundation)

public extension FileStream {
  /// Reads a line from the stream and decodes it as UTF-8.
  ///
  /// - Parameter maxBytes: Maximum line length cap. Defaults to 8 MiB.
  /// - Returns: The decoded line string, or `nil` at EOF.
  /// - Throws: An error if the underlying read fails.
  mutating func readLineUTF8(maxBytes: Int = 8 * 1024 * 1024) throws -> String? {
    guard let b = try readLine(maxBytes: maxBytes) else { return nil }
    return String(decoding: b, as: UTF8.self)
  }

  /// Encodes `s` as UTF-8 and appends it to the write buffer.
  ///
  /// - Parameter s: The string to write.
  /// - Throws: An error if the underlying write or flush fails.
  mutating func writeUTF8(_ s: String) throws {
    try write(Array(s.utf8))
  }

  /// Encodes `s` as UTF-8, appends it to the write buffer, then appends a newline.
  ///
  /// - Parameter s: The string to write before the newline.
  /// - Throws: An error if the underlying write or flush fails.
  mutating func writeLineUTF8(_ s: String) throws {
    try write(Array(s.utf8))
    try putc(0x0A)
  }
}
