
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2025 using an LLM

public extension String {
  /// Returns a new string left-padded to at least `toLength` characters.
  ///
  /// If the string is already at least `toLength` characters long, it is returned unchanged.
  ///
  /// - Parameters:
  ///   - toLength: The desired minimum total length.
  ///   - withPad: The padding string to prepend. Defaults to a single space.
  /// - Returns: A padded string of at least `toLength` characters.
  func leftPad(toLength: Int, withPad: String = " ") -> String {
    guard toLength > 0 else { return self }
    guard !self.isEmpty else { return String(repeating: withPad, count: toLength) }
    let paddingNeeded = toLength - self.count
    guard paddingNeeded > 0 else { return self }
    return String(repeating: withPad, count: paddingNeeded) + self
  }

  /// Returns a new string right-padded to at least `toLength` characters.
  ///
  /// If the string is already at least `toLength` characters long, it is returned unchanged.
  ///
  /// - Parameters:
  ///   - toLength: The desired minimum total length.
  ///   - withPad: The padding string to append. Defaults to a single space.
  /// - Returns: A padded string of at least `toLength` characters.
  func rightPad(toLength: Int, withPad: String = " ") -> String {
    guard toLength > 0 else { return self }
    guard !self.isEmpty else { return String(repeating: withPad, count: toLength) }
    let paddingNeeded = toLength - self.count
    guard paddingNeeded > 0 else { return self }
    return self + String(repeating: withPad, count: paddingNeeded)
  }
}
