
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2025 using an LLM

import Darwin

public extension String {
  /// Returns a new string left-padded to at least `toLength` characters.
  ///
  /// If the string is already at least `toLength` characters long, it is returned unchanged.
  ///
  /// - Parameters:
  ///   - toLength: The desired minimum total length.
  ///   - withPad: The padding string to prepend. Defaults to a single space.
  /// - Returns: A padded string of at least `toLength` characters.
  func leftPad(toLength: Int, withPad: String = " ") -> String {
    guard toLength > 0 else { return self }
    guard !self.isEmpty else { return String(repeating: withPad, count: toLength) }
    let paddingNeeded = toLength - self.count
    guard paddingNeeded > 0 else { return self }
    return String(repeating: withPad, count: paddingNeeded) + self
  }

  /// Returns a new string right-padded to at least `toLength` characters.
  ///
  /// If the string is already at least `toLength` characters long, it is returned unchanged.
  ///
  /// - Parameters:
  ///   - toLength: The desired minimum total length.
  ///   - withPad: The padding string to append. Defaults to a single space.
  /// - Returns: A padded string of at least `toLength` characters.
  func rightPad(toLength: Int, withPad: String = " ") -> String {
    guard toLength > 0 else { return self }
    guard !self.isEmpty else { return String(repeating: withPad, count: toLength) }
    let paddingNeeded = toLength - self.count
    guard paddingNeeded > 0 else { return self }
    return self + String(repeating: withPad, count: paddingNeeded)
  }

  /// Formats a single string argument using a C-style `printf` format.
  ///
  /// This overload avoids the overhead of a variadic `va_list` when exactly one
  /// `String` argument is needed.
  ///
  /// - Parameters:
  ///   - format: A `printf`-style format string with a single `%s` specifier.
  ///   - args: The string argument.
  /// - Returns: The formatted string.
  func cFormat(_ args : CVarArg...) -> String {
    return cFormat(self, args)
  }

  /// Formats a string using a C-style `printf` format and a variadic argument list.
  ///
  /// The output is decoded as ISO Latin-1 to preserve non-ASCII byte values.
  ///
  /// - Parameters:
  ///   - format: A `printf`-style format string.
  ///   - args: Zero or more `CVarArg` values matching the format specifiers.
  /// - Returns: The formatted string.
  func cFormat(_ args : [CVarArg]) -> String {
    for (i,a) in args.enumerated() {
      if a is String {
        return (a as! String).withCString {
          let newa = args[0..<i] + [$0] + args[i+1..<args.count]
          return cFormat(Array(newa))
        }
      }
    }

    let bufferSize = withVaList(args) { vaList in
      1+Int(vsnprintf(nil, 0, self, vaList))
    }
    return withUnsafeTemporaryAllocation(of: UInt8.self, capacity: bufferSize) { ptr in
      let n = withVaList(args) { vaPtr in
        vsnprintf(ptr.baseAddress, bufferSize, self, vaPtr)
      }
      let pp = UnsafeBufferPointer(start: ptr.baseAddress!, count: Int(n) )
      return String(decoding: pp, as: ISOLatin1.self)
    }
  }
}
