
// Generated by Robert M. Lefkowitz <code@liberally.net> in 2024 using an LLM
// from files containing the following notices:

/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (c) 1987, 1993, 1994
 *  The Regents of the University of California.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*
 * Copyright (c) 2002 Todd C. Miller <Todd.Miller@courtesan.com>
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 * Sponsored in part by the Defense Advanced Research Projects
 * Agency (DARPA) and Air Force Research Laboratory, Air Force
 * Materiel Command, USAF, under agreement number F39502-99-1-0512.
 */

/*
 * Copyright (c) 2000 The NetBSD Foundation, Inc.
 * All rights reserved.
 *
 * This code is derived from software contributed to The NetBSD Foundation
 * by Dieter Baron and Thomas Klausner.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

import Darwin

/// Specifies whether a long option requires, forbids, or optionally accepts an argument.
public enum argType: Int32, Sendable {
  /// The option takes no argument.
  case no_argument = 0
  /// The option requires an argument.
  case required_argument = 1
  /// The option accepts an optional argument.
  case optional_argument = 2
}

/// A single entry in a long-option table, describing the option's name and argument requirement.
public struct LongOption : Sendable {
  /// The long option name (without leading `--`).
  public let name: String
  /// Whether the option takes no, required, or optional argument.
  public let has_arg: argType

  /// Creates a `LongOption` with the given name and argument type.
  ///
  /// - Parameters:
  ///   - n: The long option name.
  ///   - h: Whether the option takes an argument.
  public init(_ n: String, _ h: argType) {
    self.name = n
    self.has_arg = h
  }
}

/// A Swift reimplementation of BSD `getopt_long(3)` / `getopt_long_only(3)`.
///
/// `BSDGetopt_long` parses POSIX-style and GNU-style long options from an
/// argument array.  Create an instance with an option string, a ``LongOption``
/// table, and (optionally) an explicit argument array.  Call ``getopt_long()``
/// (or ``getopt_long_only()``) in a loop until it returns `nil`.
///
/// Each successful call returns a tuple `(optionName, argument)` where
/// `optionName` is either the matched long-option name or a single-character
/// short-option string.
public class BSDGetopt_long {

  /// Current index into the argument array (equivalent to POSIX `optind`).
  var optind = 0

  /// Internal flags controlling argument permutation and matching mode.
  struct GLFlags: OptionSet {
    let rawValue: UInt8

    /// Permute non-option arguments to the end of the array.
    static let FLAG_PERMUTE = GLFlags(rawValue: 0x01)
    /// Treat non-option arguments as arguments to the special option `"-1"`.
    static let FLAG_ALLARGS = GLFlags(rawValue: 0x02)
    /// Operate as `getopt_long_only`, allowing long options with a single `-` prefix.
    static let FLAG_LONGONLY = GLFlags(rawValue: 0x04)
  }

  /// The character returned for a bad argument (`":"` or `"?"`).
  let BADARG: String

  /// When `true`, unknown-option errors are suppressed.
  var opterr = true

  /// Sentinel returned as the option name when `FLAG_ALLARGS` is active and a non-option is seen.
  let INORDER = "\u{01}"

  /// The option-definition string (e.g. `"abc:d::"` for `getopt`).
  var options: String
  /// The long-option table.
  var long_options: [LongOption]
  /// The argument array being parsed.
  var nargv: [String]

  /// Whether POSIX-mode parsing is in effect (non-options stop parsing).
  var posixly_correct: Bool

  /// The last unrecognised option character.
  var optopt: Character = "?"
  /// The argument associated with the most recently parsed option.
  var optarg: String = ""

  let NO_PREFIX = -1
  let D_PREFIX = 0
  let DD_PREFIX = 1
  let W_PREFIX = 2

  /// Index of the first non-option argument encountered (for permutation).
  var nonopt_start = -1
  /// Index of the first option argument after a run of non-options (for permutation).
  var nonopt_end = -1

  /// Records which dash prefix was used when a long option was detected.
  var dash_prefix = -1  // NO_PREFIX

  /// The portion of the current argument that has not yet been consumed.
  var place = ""

  /// Creates a `BSDGetopt_long` parser.
  ///
  /// - Parameters:
  ///   - s: The option-definition string in `getopt(3)` format.
  ///   - long_options: The long-option table.
  ///   - args: The argument array to parse. Defaults to `CommandLine.arguments` (minus `argv[0]`).
  public init(
    _ s: String, _ long_options: [LongOption],
    _ args: [String] = Array(CommandLine.arguments.dropFirst())
  ) {
    self.options = s
    self.nargv = args
    self.long_options = long_options
    optind = 0

    BADARG = s.first == ":" ? ":" : "?"

    // Disable GNU extensions if POSIXLY_CORRECT is set or options string begins with a '+'.
    posixly_correct = getenv("POSIXLY_CORRECT") != nil
  }

  /// Computes the greatest common divisor of two integers.
  ///
  /// - Parameters:
  ///   - aa: First value.
  ///   - bb: Second value.
  /// - Returns: The GCD of `aa` and `bb`.
  func gcd(_ aa: Int, _ bb: Int) -> Int {
    var a = aa
    var b = bb
    var c = a % b
    while c != 0 {
      a = b
      b = c
      c = a % b
    }
    return b
  }

  /// Permutes the non-option arguments at `panonopt_start..<panonopt_end` to the
  /// end of the range `panonopt_start..<opt_end`, preserving relative order within
  /// both the non-option and option sub-arrays.
  ///
  /// - Parameters:
  ///   - panonopt_start: Start index of the non-option block.
  ///   - panonopt_end: One past the end of the non-option block (start of the option block).
  ///   - opt_end: One past the end of the option block.
  ///   - nargv: The argument array to permute in place.
  func permute_args(
    _ panonopt_start: Int, _ panonopt_end: Int, _ opt_end: Int,
    _ nargv: inout [String]
  ) {
    // compute lengths of blocks and number and size of cycles
    let nnonopts = panonopt_end - panonopt_start
    let nopts = opt_end - panonopt_end
    let ncycle = gcd(nnonopts, nopts)
    let cyclelen = (opt_end - panonopt_start) / ncycle

    for i in 0..<ncycle {
      let cstart = panonopt_end + i
      var pos = cstart
      for _ in 0..<cyclelen {
        if pos >= panonopt_end {
          pos -= nnonopts
        } else {
          pos += nopts
        }

        let swap = nargv[pos]
        nargv[pos] = nargv[cstart]
        nargv[cstart] = swap
      }
    }
  }

  /// Attempts to match the current ``place`` string against the long-option table.
  ///
  /// Returns `nil` when `short_too` is set and no long match was found (so the
  /// caller can fall through to short-option parsing).  Throws on ambiguous,
  /// disallowed, or missing arguments.
  ///
  /// - Parameters:
  ///   - short_too: When `true`, a single-character string is allowed to match a short option
  ///     rather than being forced to match a long option.
  ///   - flags: Internal ``GLFlags`` controlling behaviour.
  /// - Returns: A `(name, argument)` tuple on success, or `nil` if no long match and `short_too`.
  /// - Throws: ``CmdErr`` for ambiguous abbreviations, disallowed arguments, or missing arguments.
  func
    parse_long_options(_ short_too: Bool, _ flags: GLFlags) throws(CmdErr) -> (
      String, String
    )?
  {
    var current_dash: String = ""

    let cur_argv = place

    switch dash_prefix {
    case D_PREFIX:
      current_dash = "-"
    case DD_PREFIX:
      current_dash = "--"
    case W_PREFIX:
      current_dash = "-W "
    default:
      current_dash = ""
    }

    var match = -1
    var exact_match = false
    var second_partial_match = false

    optind += 1

    var current_key: String

    let has_equal = cur_argv.firstIndex(of: "=")
    if let has_equal {
      // argument found (--option=arg)
      current_key = String(cur_argv.prefix(upTo: has_equal))
    } else {
      current_key = cur_argv
    }

    for (i, opt) in long_options.enumerated() {
      /* find matching long option */
      if !opt.name.hasPrefix(current_key) {
        continue
      }

      if opt.name.count == current_key.count {
        /* exact match */
        match = i
        exact_match = true
        break
      }

      // If this is a known short option, don't allow a partial match of a single character.
      if short_too && current_key.count == 1 {
        continue
      }

      if match == -1 { // first partial match
        match = i
      } else if flags.contains(.FLAG_LONGONLY)
        || long_options[i].has_arg != long_options[match].has_arg
      {
        second_partial_match = true
      }
    }
    if !exact_match && second_partial_match {
      // ambiguous abbreviation
      throw CmdErr(1, "option \(current_dash)\(current_key) is ambiguous")
    }

    if match != -1 { // option found
      if let _ = has_equal, long_options[match].has_arg == .no_argument {
        throw CmdErr(
          1, "option \(current_dash)\(current_key) doesn't allow an argument")
      }
      if long_options[match].has_arg == .required_argument
        || long_options[match].has_arg == .optional_argument
      {
        if let has_equal {
          optarg = String(place.suffix(from: has_equal).dropFirst())
        } else if long_options[match].has_arg == .required_argument {
          // optional argument doesn't use next nargv
          optarg = nargv[optind]
          optind += 1
        }
      }
      if long_options[match].has_arg == .required_argument && optarg == "" {
        /*
         * Missing argument; leading ':' indicates no error
         * should be generated.
         */
        optind -= 1
        throw CmdErr(1, "option \(current_dash)\(current_key) requires an argument")
      }
    } else { // unknown option
      if short_too {
        optind -= 1
        return nil
      }
      throw CmdErr(1, "unrecognized option \(current_dash)\(current_key)")
    }

    return (long_options[match].name, optarg)
  }

  // -=================================================================================================================

  /// Core option-parsing engine shared by ``getopt_long()`` and ``getopt_long_only()``.
  ///
  /// - Parameter flagsx: Internal flags controlling permutation and long-only mode.
  /// - Returns: A `(optionName, argument)` tuple, or `nil` when all options are consumed.
  /// - Throws: ``CmdErr`` for any option-parsing error.
  func getopt_internal(_ flagsx: GLFlags) throws(CmdErr) -> (String, String)? {

    var optchar: String = "?"
    var short_too = false

    var flags = flagsx
    if options.first == "-" {
      flags.formUnion(.FLAG_ALLARGS)
    } else if posixly_correct || options.first == "+" {
      flags.remove(.FLAG_PERMUTE)
    }
    if options.first == "+" || options.first == "-" {
      options.removeFirst()
    }

    while true {
      // start:
      if place.isEmpty { // update scanning pointer
        if optind >= nargv.count { // end of argument vector
          place = ""
          if nonopt_end != -1 {
            // do permutation, if we have to
            permute_args(nonopt_start, nonopt_end, optind, &nargv)
            optind -= nonopt_end - nonopt_start
          } else if nonopt_start != -1 {
            // If we skipped non-options, set optind to the first of them.
            optind = nonopt_start
          }
          nonopt_start = -1
          nonopt_end = -1
          return nil
        }

        place = nargv[optind]
        if place.first != "-" || place.count == 1 {
          place = "" /* found non-option */
          if flags.contains(.FLAG_ALLARGS) {
            // GNU extension: return non-option as argument to option 1
            optarg = nargv[optind]
            optind += 1
            return (INORDER, optarg)
          }
          if !flags.contains(.FLAG_PERMUTE) {
             // If no permutation wanted, stop parsing at first non-option.
            return nil
          }
          // do permutation
          if nonopt_start == -1 {
            nonopt_start = optind
          } else if nonopt_end != -1 {
            permute_args(nonopt_start, nonopt_end, optind, &nargv)
            nonopt_start = optind - (nonopt_end - nonopt_start)
            nonopt_end = -1
          }
          optind += 1
          // process next argument
          continue

        }

        if nonopt_start != -1 && nonopt_end == -1 {
          nonopt_end = optind
        }

        // If we have "-" do nothing, if "--" we are done.
        if place.count > 1 {
          place.removeFirst()
          if place == "-" {
            optind += 1
            place = ""

             // We found an option (--), so if we skipped non-options, we have to permute.
            if nonopt_end != -1 {
              permute_args(nonopt_start, nonopt_end, optind, &nargv)
              optind -= nonopt_end - nonopt_start
            }
            nonopt_start = -1
            nonopt_end = -1
            return nil
          }
        }
      }
      break
    }
    /*
     * Check long options if:
     *  1) we were passed some
     *  2) the arg is not just "-"
     *  3) either the arg starts with -- we are getopt_long_only()
     */
    if place != nargv[optind]
      && (place.first == "-" || flags.contains(.FLAG_LONGONLY))
    {
      short_too = false

      dash_prefix = D_PREFIX

      if place.first == "-" {
        place.removeFirst() /* --foo long option */
        if place.isEmpty {
          throw CmdErr(1, "malformed option")
        }

        dash_prefix = DD_PREFIX

      } else if place.first != ":"
                  && Darwin.strchr(options, Int32(UnicodeScalar(place.first!.asciiValue!).value))
          != nil
      {
        short_too = true /* could be short option too */
      }

      if let k = try parse_long_options(short_too, flags) {
        place = ""
        return k
      }
    }

    let oc = place.removeFirst()
    var oli: Character?
    var oli2: Character?
    var oli3: Character?
    if let oo = options.firstIndex(of: oc) {
      let olix = options.suffix(from: oo)
      oli = olix.first
      oli2 = olix.dropFirst().first
      oli3 = olix.dropFirst(2).first
    }
    optchar = String(oc)

    if optchar == ":" || (optchar == "-" && !place.isEmpty) || oli == nil {
      /*
       * If the user specified "-" and  '-' isn't listed in
       * options, return -1 (non-option) as per POSIX.
       * Otherwise, it is an unknown option character (or ':').
       */
      if optchar == "-" && place.isEmpty {
        return nil
      }
      if place.isEmpty {
        optind += 1
      }
      throw CmdErr( 1, posixly_correct ? 
                    "illegal option -- \(optchar)"
                    : "invalid option -- \(optchar)")
    }
    if optchar == "W" && oli2 == ";" {
      // -W long-option
      if !place.isEmpty { // no space
        // NOTHING
      } else {
        optind += 1
        if optind >= nargv.count { // no arg
          place = ""
          throw CmdErr(1, "option requires an argument -- \(optchar)")
        } else { // white space
          place = nargv[optind]
        }
      }

      dash_prefix = W_PREFIX

      return try parse_long_options(false, flags)
    }
    if oli2 != ":" { // doesn't take argument
      if place.isEmpty {
        optind += 1
      }
    } else { // takes (optional) argument
      optarg = ""
      if !place.isEmpty { // no white space
        optarg = place
      } else if oli3 != ":" { // arg not optional
        optind += 1
        if optind >= nargv.count { // no arg
          place = ""

          throw CmdErr(1, "option requires an argument -- \(optchar)")
        } else {
          optarg = nargv[optind]
        }
      }
      place = ""
      optind += 1
    }
    // dump back option letter and argument
    return (optchar, optarg)
  }

  /// Parses the next short or long option from the argument array, permuting non-options to the end.
  ///
  /// - Returns: A `(name, argument)` tuple, or `nil` when no more options remain.
  /// - Throws: ``CmdErr`` on malformed or unrecognised options.
  public func getopt_long() throws(CmdErr) -> (String, String)? {
    return try getopt_internal(GLFlags.FLAG_PERMUTE)
  }

  /// Like ``getopt_long()``, but also recognises long options prefixed with a single `-`.
  ///
  /// - Returns: A `(name, argument)` tuple, or `nil` when no more options remain.
  /// - Throws: ``CmdErr`` on malformed or unrecognised options.
  public func getopt_long_only() throws(CmdErr) -> (String, String)? {
    return try getopt_internal(GLFlags.FLAG_PERMUTE.union(.FLAG_LONGONLY))
  }

  /// The argument array elements that were not consumed as options (available after parsing completes).
  public var remaining: [String] {
    return Array(nargv.dropFirst(optind))
  }
}

// ===================================================================

/// A Swift reimplementation of BSD `getopt(3)`.
///
/// `BSDGetopt` parses traditional short options from an argument array.
/// Create an instance with an option-definition string, then call
/// ``getopt()`` in a loop until it returns `nil`.
public class BSDGetopt {
  /// The argument associated with the most recently parsed option.
  var optarg: String = ""

  /// The option-definition string (e.g. `"abc:d::"` where `:` means required argument and `::` means optional).
  var ostr: String
  /// The remaining argument slice being parsed.
  var nargv: ArraySlice<String>
  /// The portion of the current argument token not yet consumed.
  var place = ""

  /// The program name, taken from `argv[0]`.
  let PROGNAME = CommandLine.arguments[0]

  /// Creates a `BSDGetopt` parser.
  ///
  /// - Parameters:
  ///   - ostr: The option-definition string in `getopt(3)` format.
  ///   - args: The argument array to parse. Defaults to `CommandLine.arguments` (minus `argv[0]`).
  public init(
    _ ostr: String, args: ArraySlice<String> = CommandLine.arguments.dropFirst()
  ) {
    self.ostr = ostr
    self.nargv = args
  }

  /// The argument array elements that were not consumed as options.
  public var remaining: [String] { Array(nargv) }

  /// Discards the next `n` arguments from the front of the remaining array.
  ///
  /// - Parameter n: The number of arguments to skip. Defaults to `1`.
  public func skip(_ n: Int = 1) {
    nargv = nargv.dropFirst(n)
  }

  /// Parses the next short option.
  ///
  /// Returns `nil` when the first non-option argument is encountered or when
  /// `--` is reached, leaving unprocessed arguments in ``remaining``.
  ///
  /// - Returns: A `(optionCharacter, argument)` tuple, or `nil` when parsing is done.
  /// - Throws: ``CmdErr`` on an illegal option character or missing required argument.
  public func getopt() throws(CmdErr) -> (Character, String)? {
    var optopt: Character = "?"  // character checked for validity
    guard nargv.count > 0 else {
      return nil
    }

    if place.isEmpty {
      place = nargv.first!

      guard !place.isEmpty, place.removeFirst() == "-" else {
        // Argument is absent or is not an option
        place = ""
        return nil
      }

      if place == "-" {
        nargv.removeFirst()
        place = ""
        // "--" => end of options
        return nil
      }

      if place.isEmpty {
        // Solitary '-', treat as a '-' option if the program (eg su) is looking for it.
        if ostr.contains("-") {
          optopt = "-"
        } else {
          return nil
        }
      } else {
        optopt = place.removeFirst()
      }
    } else {
      optopt = place.removeFirst()
    }

    // See if option letter is one the caller wanted...
    if optopt == ":" || !ostr.contains(optopt) {
      if place.isEmpty {
        nargv.removeFirst()
      }
      if ostr.first != ":" {
        throw CmdErr(1, "\(PROGNAME): illegal option -- \(optopt)")
      }
    }

    // Does this option need an argument?
    if !ostr.contains("\(optopt):") {
      // don't need argument
      optarg = ""
      if place.isEmpty { nargv.removeFirst() }
    } else {
      // Option-argument is either the rest of this argument or the entire next argument.
      let gnuopt = ostr.contains("\(optopt)::" )
      if !place.isEmpty {
        optarg = place
      } else if nargv.count > 1 {
        if gnuopt && nargv[1+nargv.startIndex].first == "-" {
          optarg == ""
        } else {
          nargv.removeFirst()
          optarg = nargv.first!
        }
      } else {
        // option-argument absent
        if !nargv.isEmpty { nargv.removeFirst() }
        optarg = ""
        place = ""
        if ostr.first == ":" {
          return (":", "")
        }
        if gnuopt {
          optarg = ""
        } else {
          throw CmdErr(1, "\(PROGNAME): option requires an argument \(optopt)")
        }
      }
      place = ""
      if !nargv.isEmpty { nargv.removeFirst() }
    }
    return (optopt, optarg)  // return option letter and argument
  }
}
