
// Generated by Robert M. Lefkowitz <code@liberally.net> in 2025 using an LLM
// from a file containing the following notice:

/*  $NetBSD: humanize_number.c,v 1.14 2008/04/28 20:22:59 martin Exp $  */

/*-
 * SPDX-License-Identifier: BSD-2-Clause-FreeBSD
 *
 * Copyright (c) 1997, 1998, 1999, 2002 The NetBSD Foundation, Inc.
 * Copyright 2013 John-Mark Gurney <jmg@FreeBSD.org>
 * All rights reserved.
 *
 * This code is derived from software contributed to The NetBSD Foundation
 * by Jason R. Thorpe of the Numerical Aerospace Simulation Facility,
 * NASA Ames Research Center, by Luke Mewburn and by Tomas Svensson.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE NETBSD FOUNDATION, INC. AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 * TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

// FIXME: This came from Libutil
// if libutil is ported completely, this should go there.

/// Formatting flags for ``humanize_number(_:_:_:_:_:)``.
///
/// Mirrors the `HN_*` constants from BSD's `<libutil.h>`.
public struct HumanizeFlags : OptionSet, Sendable {
  /// The raw integer bitmask.
  public let rawValue: Int

  /// Creates a `HumanizeFlags` from a raw bitmask value.
  public init(rawValue: Int) {
    self.rawValue = rawValue
  }

  /// Display a decimal fraction when the value rounds to less than 10 (e.g. `1.5 K`).
  public static let decimal = Self(rawValue: 1 << 0)
  /// Suppress the space between the number and the unit prefix (e.g. `1.5K` instead of `1.5 K`).
  public static let nospace = Self(rawValue: 1 << 1)
  /// Include a `B` (bytes) suffix at scale 0.
  public static let b = Self(rawValue: 1 << 2)
  /// Use 1000 as the divisor instead of 1024.
  public static let divisor_1000 = Self(rawValue: 1 << 3)
  /// Use IEC binary prefixes (`Ki`, `Mi`, `Gi`, …) instead of the traditional ones.
  public static let iec_prefixes = Self(rawValue: 1 << 4)
}

fileprivate typealias HFS = (divisor: Int, scale: Int, divisordeccut : Int)
fileprivate let maxscale = 6

/// Formats a byte count as a human-readable string with an appropriate SI/binary prefix.
///
/// Mirrors the BSD `humanize_number(3)` function.
///
/// - Parameters:
///   - len: The total number of characters available in the output buffer (governs which
///     scale is chosen automatically when `scale` is `nil`).
///   - quotientx: The integer value to format (typically a byte count).
///   - suffix: A suffix string appended after the prefix (e.g. `"B"` for bytes).
///   - scale: An explicit scale index (0 = bytes, 1 = K, …, 6 = E); pass `nil` to
///     auto-scale so the result fits within `len` characters.
///   - flags: Formatting options; see ``HumanizeFlags``.
/// - Returns: The formatted string, or `nil` if the value cannot fit in `len` characters
///   or if contradictory flags are supplied.
public func humanize_number(_ len : Int, _ quotientx : Int, _ suffix : String, _ scale : UInt?, _ flags : HumanizeFlags) -> String? {
  var scx : Int
  if let sx = gshn(len, quotientx, suffix, flags) {
    if let scale {
      if scale > maxscale { return nil }
      scx = Int(scale)
    } else {
      scx = sx
    }
    return hn(len, quotientx, suffix, scx, flags)
  } else {
    return nil
  }
}

/// Computes the automatic scale index for ``humanize_number(_:_:_:_:_:)``.
///
/// Returns `nil` when the value cannot be represented within `len` characters,
/// or when mutually exclusive flags are set.
fileprivate func gshn(_ len : Int, _ quotientx : Int, _ suffix : String, _ flags : HumanizeFlags) -> Int? {
  var quotient = quotientx

  if flags.contains(.divisor_1000) && flags.contains(.iec_prefixes) {
    return nil
  }

  var (divisor, divisordeccut, _, baselen) = gp(flags, 0)

  if quotient < 0 {
    quotient = -quotient
    baselen += 2
  } else {
    baselen += 1
  }
  if flags.contains(.nospace) {
  } else {
    baselen += 1
  }
  baselen += suffix.count

  if len < baselen + 1 {
    return nil
  }

  var ii = len - baselen

  var max = 1
  while ii > 0 && max <= Int.max / 10 {
    ii -= 1
    max *= 10
  }

  var remainder = 0
  var i = 0
  while
      (quotient >= max || (quotient == max - 1 &&
                           (remainder >= divisordeccut || remainder >=
                            divisor / 2))) && i < maxscale {
    remainder = quotient % divisor;
    quotient /= divisor;
    i += 1
  }

  return i
}

fileprivate typealias GP = (divisor: Int, divisordeccut: Int, prefix: String, baselen : Int)

/// Returns the divisor, decimal-cut threshold, prefix string, and base length for the given flags and scale.
fileprivate func gp(_ flags: HumanizeFlags, _ scale : Int) -> GP {
  var prefixes : [String]
  var divisor : Int
  var divisordeccut : Int

  func scale2prefix(_ scale : Int) -> String {
    prefixes[scale]
  }

  var baselen : Int

  if flags.contains(.iec_prefixes) {
    baselen = 2
    divisor = 1024
    divisordeccut = 973  /* ceil(.95 * 1024) */
    if flags.contains(.b) {
      prefixes = ["B", "Ki", "Mi", "Gi", "Ti", "Pi", "Ei"]
    }
    else {
      prefixes = ["", "Ki", "Mi", "Gi", "Ti", "Pi", "Ei"]
    }
  } else {
    baselen = 1
    if flags.contains(.divisor_1000) {
      divisor = 1000
      divisordeccut = 950
      if flags.contains(.b) {
        prefixes = ["B", "k", "M", "G", "T", "P", "E"]
      } else {
        prefixes = ["", "k", "M", "G", "T", "P", "E"]
      }
    } else {
      divisor = 1024
      divisordeccut = 973  /* ceil(.95 * 1024) */
      if flags.contains(.b) {
        prefixes = ["B", "K", "M", "G", "T", "P", "E"]
      } else {
        prefixes = ["", "K", "M", "G", "T", "P", "E"]
      }
    }
  }
  return (divisor: divisor, divisordeccut: divisordeccut, prefix: scale2prefix(scale), baselen: baselen)
}

import locale_h

/// Formats the value using a pre-computed scale and returns the final string.
fileprivate func hn(_ len : Int, _ quotientx : Int, _ suffix : String, _ scale : Int, _ flags : HumanizeFlags) -> String? {

  var quotient = quotientx
  var remainder = 0
  var (divisor, divisordeccut, prefix, _) = gp(flags, scale)

  var sign : Int
  var sep : String

  if quotient < 0 {
    sign = -1
    quotient = -quotient
  } else {
    sign = 1;
  }
  if flags.contains(.nospace) {
    sep = ""
  } else {
    sep = " ";
  }

  for i in 0..<scale {
    remainder = quotient % divisor;
    quotient /= divisor;
  }

  var i = scale

  if ((quotient == 9 && remainder < divisordeccut) || quotient < 9) &&
      i > 0 && flags.contains(.decimal) {
    let s1 = quotient + ((remainder * 10 + divisor / 2) / divisor / 10)
    let s2 = ((remainder * 10 + divisor / 2) / divisor) % 10
    var dd : String = "."
    if let decpt = localeconv()?.pointee.decimal_point.pointee {
      dd = String(decpt)
    }

    return "\(sign * s1)\(dd)\(s2)\(sep)\(prefix)\(suffix)"
  } else {
    return  "\(sign * (quotient + (remainder + divisor / 2) / divisor))\(sep)\(prefix)\(suffix)"
  }
}
