
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2025

import Darwin

/// The result of matching a user's response against locale-defined yes/no patterns.
public enum YesNo {
  /// The response matches the locale's "yes" pattern.
  case yes
  /// The response matches the locale's "no" pattern.
  case no
  /// The response does not match either pattern.
  case neither
}

/// Matches a user response string against the locale's yes/no regular expressions.
///
/// Uses `nl_langinfo(YESEXPR)` and `nl_langinfo(NOEXPR)` to obtain locale-appropriate
/// patterns, falling back to `^[yY]` and `^[nN]` respectively.
///
/// - Parameter resp: The user-supplied response string to test.
/// - Returns: `.yes` if the response matches the yes pattern, `.no` if it matches
///   the no pattern, or `.neither` for any other input.
public func rpmatch(_ resp : String) -> YesNo {
  let rpy = String(validatingCString: nl_langinfo(YESEXPR)) ?? "^[yY]"
  let py = try? Regex(rpy)

  let rpn = String(validatingCString: nl_langinfo(NOEXPR)) ?? "^[nN]"
  let pn = try? Regex(rpn)

  if let _ = try? py?.firstMatch(in: resp) {
    return .yes
  }
  if let _ = try? pn?.firstMatch(in: resp) {
    return .no
  }
  return .neither
}
