
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2025

/// Errors that can be thrown by ``expand_number(_:)``.
public enum ExpandNumberError: Error {
  /// The input string does not match the expected numeric format.
  case invalidFormat
  /// The result would exceed the range of `UInt64`.
  case overflow
}

/// Parses a human-readable byte count string (e.g. `"512K"`, `"2G"`) into a `UInt64`.
///
/// The input is trimmed of leading whitespace, converted to uppercase, and then matched
/// against the pattern `^([0-9]+)([BKMGTPE]?)$`.  The optional suffix selects a binary
/// multiplier:
///
/// | Suffix | Multiplier |
/// |--------|-----------|
/// | B      | 1         |
/// | K      | 1,024     |
/// | M      | 1,048,576 |
/// | G      | 1,073,741,824 |
/// | T      | 1,099,511,627,776 |
/// | P      | 1,125,899,906,842,624 |
/// | E      | 1,152,921,504,606,846,976 |
///
/// - Parameter input: A string containing a non-negative integer followed by an optional
///   suffix character.
/// - Returns: The byte count as a `UInt64`.
/// - Throws: ``ExpandNumberError/invalidFormat`` if the string cannot be parsed,
///   or ``ExpandNumberError/overflow`` if the result overflows `UInt64`.
public func expand_number(_ input: String) throws -> UInt64 {
    let suffixMultipliers: [Character: UInt64] = [
        "B": 1,         // Bytes
        "K": 1024,      // Kilobytes
        "M": 1024 * 1024, // Megabytes
        "G": 1024 * 1024 * 1024, // Gigabytes
        "T": 1024 * 1024 * 1024 * 1024, // Terabytes
        "P": 1024 * 1024 * 1024 * 1024 * 1024, // Petabytes
        "E": 1024 * 1024 * 1024 * 1024 * 1024 * 1024 // Exabytes
    ]

  let trimmed = input.drop { $0.isWhitespace || $0.isNewline }.uppercased()
    let regex = try! Regex("^([0-9]+)([BKMGTPE]?)$")

    guard let match = try regex.firstMatch(in: trimmed) else {
        throw ExpandNumberError.invalidFormat
    }

  guard let numberString = match.output[1].substring else {
    throw ExpandNumberError.invalidFormat
  }

    guard let number = UInt64(numberString) else {
        throw ExpandNumberError.invalidFormat
    }

    var multiplier: UInt64 = 1
  if let mr = match.output[2].range {
      if let suffix = trimmed[mr].first {
        multiplier = suffixMultipliers[suffix] ?? 1
      } else {
          multiplier = 1
      }
    }

    let result = number.multipliedReportingOverflow(by: multiplier)
    if result.overflow {
        throw ExpandNumberError.overflow
    }

    return result.partialValue
}


