
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2025

import System
import Darwin

/// The captured standard output and standard error of a completed subprocess.
public struct ProcessResult : Sendable {
  /// The text written to standard output by the subprocess.
  public let stdout: String
  /// The text written to standard error by the subprocess.
  public let stderr: String
}

/// Errors thrown by ``ProcessRunner`` when a subprocess fails.
public enum ProcessError: Error, CustomStringConvertible {
  /// The subprocess exited with a non-zero status code.
  ///
  /// - Parameters:
  ///   - code: The exit status.
  ///   - stdout: The captured standard output.
  ///   - stderr: The captured standard error.
  case nonZeroExit(code: Int32, stdout: String, stderr: String)

  /// `posix_spawn` itself failed before the child could be started.
  ///
  /// - Parameter errno: The `errno` value set by `posix_spawn`.
  case spawnFailed(errno: Int32)

  /// A human-readable description of the error.
  public var description: String {
    switch self {
    case .nonZeroExit(let code, let out, let err):
      return "Process failed with exit code \(code).\nstdout:\n\(out)\nstderr:\n\(err)"
    case .spawnFailed(let errno):
      return "posix_spawn failed with errno \(errno): \(String(cString: strerror(errno)))"
    }
  }
}

/// Spawns a subprocess and optionally captures its standard output and standard error.
///
/// Construct a `ProcessRunner` with the command path and arguments, then call
/// ``run(input:prelaunch:captureStdout:captureStderr:)`` to execute it.  The
/// returned ``ProcessResult`` contains the captured output.
///
/// > Note: The older synchronous `ProcessRunner.run(command:…)` static method has been
/// > commented out and replaced with this instance-based async API.
public struct ProcessRunner {
  /// The path (or name) of the executable to spawn.
  var command : String
  /// Command-line arguments passed to the executable.
  var arguments: [String]
  /// An optional environment dictionary; if `nil`, the parent environment is inherited.
  var environment : [String : String]?
  /// An optional working directory; if `nil`, the child inherits the parent's directory.
  var currentDirectory : String?

  /// Creates a `ProcessRunner` configured with the given parameters.
  ///
  /// - Parameters:
  ///   - command: The executable path or name (resolved via `PATH` if not absolute).
  ///   - arguments: Arguments passed to the executable.
  ///   - currentDirectory: Optional working directory for the child process.
  ///   - environment: Optional environment dictionary; `nil` inherits the parent's environment.
  public init(command: String, arguments: [String], currentDirectory: String? = nil, environment: [String: String]? = nil) {
    self.command = command
    self.arguments = arguments
    self.environment = environment
    self.currentDirectory = currentDirectory
  }

  /// Spawns the process and asynchronously waits for it to exit.
  ///
  /// - Parameters:
  ///   - input: Optional data to feed to the child's standard input; may be a `String`,
  ///     `[UInt8]`, `AsyncStream<UInt8>`, or `FileDescriptor`.  Pass `nil` to inherit
  ///     the parent's standard input.
  ///   - prelaunch: An optional async closure called with the child's PID immediately
  ///     after `posix_spawn` succeeds (useful for attaching a debugger, etc.).
  ///   - captureStdout: If `true` (the default), standard output is captured and
  ///     returned in ``ProcessResult/stdout``.
  ///   - captureStderr: If `true` (the default), standard error is captured and
  ///     returned in ``ProcessResult/stderr``.
  /// - Returns: A ``ProcessResult`` containing the captured output.
  /// - Throws: ``ProcessError/spawnFailed(errno:)`` if `posix_spawn` fails, or
  ///   ``ProcessError/nonZeroExit(code:stdout:stderr:)`` if the child exits non-zero.
  public func run(
    input: (any Stdinable)? = nil,
    prelaunch: (@Sendable (pid_t) async -> ())? = nil,
    captureStdout: Bool = true,
    captureStderr: Bool = true) async throws -> ProcessResult {

    var stdinPipe : (readEnd: FileDescriptor, writeEnd: FileDescriptor)? = nil
    if input == nil {
      stdinPipe = try FileDescriptor.pipe()
    }

    var stdoutPipe : (readEnd: FileDescriptor, writeEnd: FileDescriptor)? = nil

    if captureStdout {
      stdoutPipe = try FileDescriptor.pipe()
    }

    var stderrPipe : (readEnd: FileDescriptor, writeEnd: FileDescriptor)? = nil

    if captureStderr {
      stderrPipe = try FileDescriptor.pipe()
    }

    defer {
      try? stdoutPipe?.readEnd.close()
      try? stdoutPipe?.writeEnd.close()
      try? stderrPipe?.readEnd.close()
      try? stderrPipe?.writeEnd.close()
    }

    var fileActions: posix_spawn_file_actions_t?
    posix_spawn_file_actions_init(&fileActions)

    if let cwd = currentDirectory {
      #if os(macOS)
      posix_spawn_file_actions_addchdir_np(&fileActions, cwd)
      #endif
    }

    switch input {
      case nil:
        posix_spawn_file_actions_adddup2(&fileActions,  FileDescriptor.standardInput.rawValue, STDIN_FILENO)
      case is FileDescriptor:
posix_spawn_file_actions_adddup2(&fileActions, (input as! FileDescriptor).rawValue, STDIN_FILENO)
      default:
        posix_spawn_file_actions_adddup2(&fileActions, stdinPipe!.readEnd.rawValue, STDIN_FILENO)
    }

    if captureStdout {
      posix_spawn_file_actions_adddup2(&fileActions, stdoutPipe!.writeEnd.rawValue, STDOUT_FILENO)
      posix_spawn_file_actions_addclose(&fileActions, stdoutPipe!.readEnd.rawValue)
    }

    if captureStderr {
      posix_spawn_file_actions_adddup2(&fileActions, stderrPipe!.writeEnd.rawValue, STDERR_FILENO)
      posix_spawn_file_actions_addclose(&fileActions, stderrPipe!.readEnd.rawValue)
    }

    let argv: [UnsafeMutablePointer<CChar>?] = ([command]+arguments).map { strdup($0) } + [nil]

    var pid: pid_t = 0

    var ev = environ
    if let environment {
      ev = UnsafeMutablePointer<UnsafeMutablePointer<CChar>?>.allocate(capacity: environment.count + 1)
      var i = 0
      for (k, v) in environment {
        ev[i] = strdup("\(k)=\(v)")
        i += 1
      }
      ev[i] = nil
    }

    let cc = searchPath(for: command)

    let spawnResult = posix_spawn(&pid, cc, &fileActions, nil, argv, ev)

    for ptr in argv where ptr != nil {
      free(ptr)
    }

    posix_spawn_file_actions_destroy(&fileActions)

    guard spawnResult == 0 else {
      throw ProcessError.spawnFailed(errno: spawnResult)
    }

    if let prelaunch { let p = pid; Task { await prelaunch(p) } }

    var stdo : String = ""
    var stde : String = ""

    if let ii = input {
      Task.detached {
        switch ii {
          case is [UInt8]:
            let w = stdinPipe!.writeEnd
            try w.writeAll(ii as! [UInt8])
          case is String:
            var j = ii as! String
            let w = stdinPipe!.writeEnd
            let n = try j.withUTF8 { bp in
              try w.writeAll(UnsafeRawBufferPointer(bp) )
            }
          case is AsyncStream<UInt8>:
            var j = ii as! AsyncStream<UInt8>
            let w = stdinPipe!.writeEnd
            for try await i in j {
              try w.write([i])
            }
          case is FileDescriptor:
            break
          default:
            fatalError("Unsupported input type \(type(of: ii))")
        }
      }
    }
    if captureStdout {
      try stdoutPipe!.writeEnd.close()
      stdo = try readAll(from: stdoutPipe!.readEnd)
    }
    if captureStderr {
      try stderrPipe!.writeEnd.close()
      stde = try readAll(from: stderrPipe!.readEnd)
    }

    let status = try await waitpidAsync(pid)
    let exitCode = WIFEXITED(status) ? WEXITSTATUS(status) : -1

    if exitCode != 0 {
      throw ProcessError.nonZeroExit(code: exitCode, stdout: stdo, stderr: stde)
    }

    return ProcessResult(stdout: stdo, stderr: stde)
  }

  /// Reads all available bytes from `fd` into a UTF-8 string.
  private func readAll(from fd: FileDescriptor) throws -> String {
    var output = ""
    var buffer = [UInt8](repeating: 0, count: 4096)

    while true {
      let bytesRead = try buffer.withUnsafeMutableBytes {
        try fd.read(into: $0)
      }
      if bytesRead == 0 { break }
      output += String(decoding: buffer[..<bytesRead], as: UTF8.self)
    }

    return output
  }

  /// Asynchronously waits for the process with the given PID to exit.
  ///
  /// Wraps `waitpid(2)` in a `CheckedThrowingContinuation` so it can be awaited.
  ///
  /// - Parameters:
  ///   - pid: The process ID to wait for.
  ///   - options: POSIX wait options (e.g. `WNOHANG`, `WUNTRACED`). Defaults to 0.
  /// - Returns: The raw wait status from `waitpid`.
  /// - Throws: ``POSIXErrno`` if `waitpid` returns an error.
  private func waitpidAsync(_ pid: pid_t, options: CInt = 0) async throws -> CInt {
    return try await withCheckedThrowingContinuation { continuation in
      var status: CInt = 0
      let result = waitpid(pid, &status, options)

      if result == -1 {
        continuation.resume(throwing: POSIXErrno())
      } else {
        continuation.resume(returning: status)
      }
    }
  }
}
