
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2026

public extension OptionSet {
  /// Returns `true` if `self` contains any of the options present in `of`.
  ///
  /// - Parameter of: An `OptionSet` whose members are checked for intersection with `self`.
  /// - Returns: `true` if the intersection of `self` and `of` is non-empty.
  func containsAny(of: Self) -> Bool {
    return !self.intersection(of).isEmpty
  }
}
