
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2025

import System
import Darwin

import os

/// Shared `os.Logger` used by CMigration's process-related helpers.
let logger = Logger(subsystem: "CMigration", category: "Process")

/// Logs a string message at the `info` level.
///
/// - Parameter message: The message to log.
func log(_ message: String) {
  logger.info("\(message)")
}

/// Logs a ``POSIXErrno`` error at the `error` level and returns it unchanged.
///
/// - Parameter message: The error to log.
/// - Returns: The same ``POSIXErrno`` value, enabling `throw log(error)` patterns.
func log(_ message: POSIXErrno) -> POSIXErrno {
  logger.error("\(message.localizedDescription)")
  return message
}

/// A namespace for reading and writing POSIX environment variables.
public struct Environment {
  /// Gets or sets an individual environment variable.
  ///
  /// Reading returns `nil` when the variable is unset.
  /// Assigning `nil` calls `unsetenv(3)`.
  public static subscript(_ name : String) -> String? {
    get {if let a = Darwin.getenv(name) {
      return String(cString: a)
    } else {
      return nil
    }
    }
    set {
      if let newValue {
        Darwin.setenv(name, newValue, 1)
      } else {
        Darwin.unsetenv(name)
      }
    }
  }

  /// Returns a dictionary mapping all environment variable names to their values.
  ///
  /// - Returns: A `[String: String]` snapshot of the current environment.
  public static func getenv() -> [String:String] {
    var env = [String: String]()

    var ptr = environ
    while let current = ptr.pointee {
      if let entry = String(validatingCString: current) {
        if let equalIndex = entry.firstIndex(of: "=") {
          let key = String(entry[..<equalIndex])
          let value = String(entry[entry.index(after: equalIndex)...])
          env[key] = value
        }
      }
      ptr = ptr.advanced(by: 1)
    }
    return env
  }

  /// Sets an environment variable, throwing on failure.
  ///
  /// Unlike the subscript setter, this method can propagate errors from `setenv(3)`.
  ///
  /// - Parameters:
  ///   - name: The environment variable name.
  ///   - value: The value to assign.
  /// - Throws: ``POSIXErrno`` if `setenv` returns `-1`.
  public static func setenv(_ name : String, _ value: String) throws(POSIXErrno) {
    let k = Darwin.setenv(name, value, 1)
    if k == -1 {
      throw POSIXErrno(fn: "setenv")
    }
  }

  /// Unsets an environment variable, throwing on failure.
  ///
  /// - Parameter name: The environment variable name to remove.
  /// - Throws: ``POSIXErrno`` if `unsetenv` returns `-1`.
  public static func unsetenv(_ name : String) throws(POSIXErrno) {
    let k = Darwin.unsetenv(name)
    if k == -1 {
      throw POSIXErrno(fn: "unsetenv")
    }
  }
}

/// Marker protocol for types that can be supplied as standard input to a child process.
///
/// Conforming types: `String`, `Substring`, `[UInt8]`, `FileDescriptor`, `AsyncStream`, `FilePath`.
public protocol Stdinable : Sendable {}
extension String : Stdinable {}
extension Substring : Stdinable {}
extension [UInt8] : Stdinable {}
extension FileDescriptor : Stdinable {}
extension AsyncStream : Stdinable {}
extension FilePath : Stdinable {}

/// Marker protocol for types that can be used as command-line arguments.
///
/// Conforming types implement ``asStringArgument()`` to produce the string representation
/// passed to `execv(3)`.
public protocol Arguable : Sendable {
  /// Returns the string representation of this value for use as a command-line argument.
  func asStringArgument() -> String
}
extension Substring : Arguable {
  /// Returns this substring as a `String`.
  public func asStringArgument() -> String { return String(self) }
}
extension String : Arguable {
  /// Returns `self`.
  public func asStringArgument() -> String { return self }
}
extension FilePath : Arguable {
  /// Returns the path's string representation.
  public func asStringArgument() -> String { return self.string }
}


extension FileDescriptor {
  /// Sets the close-on-exec flag (`FD_CLOEXEC`) on this file descriptor.
  func setCloexec() {
    let flags = Darwin.fcntl(self.rawValue, F_GETFD)
    _ = fcntl(self.rawValue, F_SETFD, flags | FD_CLOEXEC)
  }
}

/// An actor that wraps `posix_spawn(2)` to launch and manage a child process.
///
/// `DarwinProcess` captures stdout and stderr via pipes, optionally feeds data to
/// stdin, and exposes the combined output as an ``Output`` value.
///
/// Typical usage:
/// ```swift
/// let result = try await DarwinProcess().run("/usr/bin/sw_vers", args: "-productVersion")
/// print(result.string)
/// ```
public actor DarwinProcess {

  /// The captured output of a completed child process.
  public struct Output : Sendable {
    /// The process exit code.
    public let code : Int32
    /// The raw bytes written to standard output.
    public let data : [UInt8]
    /// The text written to standard error.
    public let error : String

    /// The standard output decoded as a UTF-8 string.
    public var string : String { String(decoding: data, as: UTF8.self) }
  }

  /// The PID of the spawned child process (0 before launch).
  public var pid : pid_t = 0
  var stdinWriteFDForParent: FileDescriptor? = nil

  var stdoutR : FileDescriptor? = nil
  var stderrR : FileDescriptor? = nil
  var feederTask : Task<Void, Error>? = nil
  var readerTask : Task<Void, Error>? = nil
  var errorTask : Task<String, Error>? = nil

  var actions: posix_spawn_file_actions_t? = nil
  var attr: posix_spawnattr_t? = nil
  var awaitingValue = false
  var launched = false

  var pendingOutput : [UInt8] = []

  /// Creates an unstarted `DarwinProcess`.
  public init() {}

  /// Sends `signal` to the child process.
  ///
  /// - Parameter n: The signal number. Defaults to `SIGTERM`.
  public func kill(_ n : Int32 = SIGTERM) {
    Darwin.kill(pid, SIGTERM)
  }

  /// Returns accumulated stdout bytes and clears the internal buffer.
  public func getOutput() -> [UInt8] {
    let k = pendingOutput
    pendingOutput = []
    return k
  }

  /// Appends bytes to the internal stdout buffer (called from the reader task).
  func appendOutput(_ b : [UInt8]) {
    pendingOutput.append(contentsOf: b)
  }

  /// Convenience static factory: creates a `DarwinProcess`, launches it, and returns it.
  ///
  /// - Parameters:
  ///   - executablePath: The executable to run.
  ///   - withStdin: Optional standard input (see ``Stdinable``).
  ///   - arguments: Command-line arguments (variadic).
  ///   - env: Extra environment variables merged over the parent's environment.
  ///   - cd: Optional working directory for the child.
  ///   - captureOutput: When `true` (default), stdout is captured.
  /// - Returns: A running `DarwinProcess`.
  /// - Throws: ``POSIXErrno`` if spawning fails.
  public static func launch(
    _ executablePath: String,
    withStdin: (any Stdinable)? = nil,
    args arguments: any Arguable...,
    env : [String : String] = [:],
    cd : FilePath? = nil,
    captureOutput: Bool = true
  ) async throws(POSIXErrno) -> DarwinProcess {
    let p = DarwinProcess()
    let _ = try await p.launch(executablePath, withStdin: withStdin, args: arguments, env: env, cd: cd, captureOutput: captureOutput)
    return p
  }

  /// Launches the process with variadic arguments (instance method).
  ///
  /// - Parameters:
  ///   - executablePath: The executable to run.
  ///   - withStdin: Optional standard input.
  ///   - arguments: Command-line arguments (variadic).
  ///   - env: Extra environment variables merged over the parent's environment.
  ///   - cd: Optional working directory.
  ///   - captureOutput: Whether to capture stdout.
  /// - Returns: The child PID.
  /// - Throws: ``POSIXErrno`` if spawning fails.
  public func launch(
    _ executablePath: String,
    withStdin: (any Stdinable)? = nil,
    args arguments: any Arguable...,
    env : [String : String] = [:],
    cd : FilePath? = nil,
    captureOutput: Bool = true
  ) throws(POSIXErrno) -> pid_t {
    return try launch(executablePath, withStdin: withStdin, args: arguments, env: env, cd: cd, captureOutput: captureOutput)
  }

  /// Core launch implementation: sets up pipes, configures `posix_spawn` file actions,
  /// spawns the child, and kicks off background I/O tasks.
  ///
  /// - Parameters:
  ///   - execu: The executable name or path (resolved via `PATH` if not absolute).
  ///   - withStdin: If non-nil, bytes are written to the child's stdin and then stdin is closed.
  ///   - arguments: Command-line arguments.
  ///   - env: Extra environment variables merged over the parent's environment.
  ///   - cd: Optional working directory (macOS only, via `posix_spawn_file_actions_addchdir_np`).
  ///   - captureOutput: When `true`, stdout is captured into ``pendingOutput``.
  /// - Returns: The child PID.
  /// - Throws: ``POSIXErrno`` if any system call fails.
  public func launch(
    _ execu: String,
    withStdin: (any Stdinable)? = nil,
    args arguments: [any Arguable] = [],
    env : [String : String] = [:],
    cd : FilePath? = nil,
    captureOutput: Bool = true
  ) throws(POSIXErrno) -> pid_t {
    // Pipes for stdout/stderr (always captured)
    if launched { fatalError("already launched once") }
    launched = true

    guard let executablePath = searchPath(for: execu) else {
      throw POSIXErrno(2, fn: "launching process")
    }

    var stdoutW : FileDescriptor? = nil
    var stderrW : FileDescriptor

    if captureOutput {
      do {
        (stdoutR, stdoutW) = try FileDescriptor.pipe()
      } catch(let e as Errno) {
        throw log(POSIXErrno(e.rawValue, fn: "pipe", reason: "creating stdout pipe"))
      } catch(let e) {
        throw log(POSIXErrno(-1, fn: "pipe", reason: "creating stdout pipe: \(e)"))
      }
        do {
          try stdoutR?.makeNonBlocking()
        } catch(let e) {
          throw POSIXErrno(e.rawValue)
        }
    }

    do {
      (stderrR, stderrW) = try FileDescriptor.pipe()
    } catch(let e as Errno) {
      throw log(POSIXErrno(e.rawValue, fn: "pipe", reason: "creating stderr pipe"))
    } catch(let e) {
      throw log(POSIXErrno(-1, fn: "pipe", reason: "creating stderr pipe: \(e)"))
    }


    // Not needed on Darwin because of SPAWN_CLOEXEC -- but needed on other platforms
    stderrR?.setCloexec()
    stderrW.setCloexec()
    stdoutR?.setCloexec()
    stdoutW?.setCloexec()


    // posix_spawn file actions are optional-opaque on Darwin in Swift
    let irc = posix_spawn_file_actions_init(&actions)
    if irc != 0 {
      throw log(POSIXErrno(irc, fn: "posix_spawn_file_actions_init"))
    }

    var openedStdinFDToCloseInParent: FileDescriptor? = nil

    switch withStdin {

      case is FilePath:
        let fp = withStdin as! FilePath
        do {
          let fd = try FileDescriptor.open(fp, .readOnly)
          openedStdinFDToCloseInParent = fd
          try addDup2AndClose(&actions, from: fd.rawValue, to: STDIN_FILENO, closeSourceInChild: false)
        } catch(let e as Errno) {
          throw log(POSIXErrno(e.rawValue, fn: "open(\(fp))", reason: "setting stdin to FilePath"))
        } catch(let e) {
          throw log(POSIXErrno(-1, fn: "open(\(fp))", reason: "setting stdin to FilePath: \(e)"))
        }
      case is FileDescriptor:
        do {
          let fd = withStdin as! FileDescriptor
          try addDup2AndClose(&actions, from: fd.rawValue, to: STDIN_FILENO, closeSourceInChild: false)
        } catch(let e as Errno) {
          throw log(POSIXErrno(e.rawValue, reason: "setting stdin to FileDescriptor" ))
        } catch(let e) {
          throw log(POSIXErrno(-1, reason: "setting stdin to FileDescriptor: \(e)"))
        }
      case is Substring, is String, is [UInt8], is AsyncStream<[UInt8]>:
        do {
          (openedStdinFDToCloseInParent, stdinWriteFDForParent) = try FileDescriptor.pipe()

          openedStdinFDToCloseInParent?.setCloexec( )
          stdinWriteFDForParent?.setCloexec()

          // Wire child's stdio
          try addDup2AndClose(&actions, from: openedStdinFDToCloseInParent!.rawValue, to: STDIN_FILENO,  closeSourceInChild: true)

          let rcCloseWrite = posix_spawn_file_actions_addclose(&actions, stdinWriteFDForParent!.rawValue)
          if rcCloseWrite != 0 { throw log(POSIXErrno(rcCloseWrite, fn: "posix_spawn_file_actions_addclose(stdin write)")) }
        } catch(let e as Errno) {
          throw log(POSIXErrno(e.rawValue, reason: "setting stdin to strings"))
        } catch(let e) {
          throw log(POSIXErrno(-1, reason: "setting stdin to strings: \(e)"))
        }

      default:
        // No stdin requested: hand the child /dev/null so reads see immediate
        // EOF instead of either inheriting the parent's stdin (which would
        // block) or being closed entirely (which would cause EBADF under
        // POSIX_SPAWN_CLOEXEC_DEFAULT).
        let rcOpenNull = "/dev/null".withCString { path in
          posix_spawn_file_actions_addopen(&actions, STDIN_FILENO, path, O_RDONLY, 0)
        }
        if rcOpenNull != 0 {
          throw log(POSIXErrno(rcOpenNull, fn: "posix_spawn_file_actions_addopen(/dev/null)"))
        }
    }

    do {
      if !captureOutput {
        let rcInheritStdout = posix_spawn_file_actions_addinherit_np(&actions, STDOUT_FILENO)
        if rcInheritStdout != 0 {
          throw log(POSIXErrno(rcInheritStdout, fn: "posix_spawn_file_actions_addinherit_np(stdout)"))
        }
      } else {
        try addDup2AndClose(&actions, from: stdoutW!.rawValue, to: STDOUT_FILENO, closeSourceInChild: true)
      }
      try addDup2AndClose(&actions, from: stderrW.rawValue, to: STDERR_FILENO, closeSourceInChild: true)
    } catch(let e as Errno) {
      throw log(POSIXErrno(e.rawValue, fn: "addDup2AndClose", reason: "redirecting stdio"))
    } catch(let e) {
      throw log(POSIXErrno(-1, fn: "addDup2AndClose", reason: "redirecting stdio: \(e)"))
    }

    if let r = stdoutR {
      let rc = posix_spawn_file_actions_addclose(&actions, r.rawValue)
      if rc != 0 { throw log(POSIXErrno(rc, fn: "posix_spawn_file_actions_addclose(stdout read)")) }
    }
    if let r = stderrR {
      let rc = posix_spawn_file_actions_addclose(&actions, r.rawValue)
      if rc != 0 { throw log(POSIXErrno(rc, fn: "posix_spawn_file_actions_addclose(stderr read)")) }
    }


    // Optional cwd (Darwin extension)
    if let cwd = cd {
#if os(macOS)
      let rc = cwd.withPlatformString { posix_spawn_file_actions_addchdir_np(&actions, $0) }
#else
      let rc = ENOTSUP
#endif
      if rc != 0 { throw log(POSIXErrno(rc, fn: "posix_spawn_file_actions_addchdir_np")) }

    }

    // Spawn
    let argvStrings = [execu] + arguments.map { $0.asStringArgument() }

    let nv = Environment.getenv().merging(env, uniquingKeysWith: { lhs, rhs in rhs} )
    let envpStrings: [String]? = nv.map { "\($0.key)=\($0.value)" }


    guard posix_spawnattr_init(&attr) == 0 else {
      throw log(POSIXErrno(fn: "posix_spawnattr_init"))
    }
    defer {
      posix_spawnattr_destroy(&attr)
    }
    var flags: Int16 = 0
    flags |= Int16(POSIX_SPAWN_SETSIGDEF)
    flags |= Int16(POSIX_SPAWN_SETSIGMASK)
    flags |= Int16(POSIX_SPAWN_CLOEXEC_DEFAULT)

    if let _ = env["SHELLDEBUGGING"] {
      flags |= Int16(POSIX_SPAWN_START_SUSPENDED)
    }

    guard posix_spawnattr_setflags(&attr, flags) == 0 else {
      throw log(POSIXErrno(fn: "posix_spawnattr_setflags"))
    }

    var sig = sigset_t()
    sigemptyset(&sig)
    posix_spawnattr_setsigdefault(&attr, &sig)
    posix_spawnattr_setsigmask(&attr, &sig)


    do {
      let spawnRC: Int32 = try withCStringArray(argvStrings) { argv in
        try withUnsafePointer(to: actions) { actionsPtr in
          try withUnsafePointer(to: attr) { attrPtr in
            if let envpStrings {
              return try withCStringArray(envpStrings) { envp in
                posix_spawn(&pid, executablePath, actionsPtr, attrPtr, argv, envp)
              }
            } else {
              return posix_spawn(&pid, executablePath, actionsPtr, attrPtr, argv, environ)
            }
          }
        }
      }
      if spawnRC != 0 {
        throw log(POSIXErrno(spawnRC, fn: "posix_spawn"))
      }
    } catch(let e as Errno) {
      throw log(POSIXErrno(e.rawValue, fn: "posix_spawn") )
    } catch(let e as POSIXErrno) {
      throw e
    } catch(let e) {
      throw log(POSIXErrno(-1, fn: "posix_spawn", reason: "\(e)"))
    }
    // Parent side: close pipe ends we must not keep open.
    // - For stdout/stderr: close the write ends in the parent (child owns those).

    do {
      try stdoutW?.close()
      try stderrW.close()
    } catch(let e as Errno) {
      let p = POSIXErrno(e.rawValue, fn: "close", reason: "closing stderrW or stdoutW" )
      throw p
    } catch(let e) {
      let p = POSIXErrno(-1, fn: "close", reason: "closing stderrW or stdoutW: \(e)" )
      throw p
    }

    // Parent closes any stdin file FD it opened (child has its own dup2'd copy).
    if let fd = openedStdinFDToCloseInParent { try? fd.close() }


    if captureOutput {
        let so = stdoutR!
        pendingOutput = []
        readerTask = Task.detached {
          while true {
            try so.waitUntilReadable()
            let res = try so.readAvailableBytes()
            if res.isEmpty {
              return
            } else {
              await self.appendOutput(res)
            }
          }
        }
    }

    let se = stderrR!
    errorTask = Task.detached {
      let res = try se.readAsString()
      return res
    }


    if let w = stdinWriteFDForParent {
      switch withStdin {
        case is String:
          let s = withStdin as! String
          feederTask = Task.detached {defer { try? w.close() }
            try w.writeAllBytes(Array(s.utf8))
          }

        case is Substring:
          let s = String(withStdin as! Substring)
          feederTask = Task.detached { defer { try? w.close() }; try w.writeAllBytes(Array(s.utf8) ) }
        case is [UInt8]:
          let b = withStdin as! [UInt8]
          feederTask = Task.detached { defer { try? w.close() }; try w.writeAllBytes(b) }
        case is AsyncStream<[UInt8]>:
          let stream = withStdin as! AsyncStream<[UInt8]>
          feederTask = Task.detached {
            defer { try? w.close() }
            for await chunk in stream {
              if Task.isCancelled { throw CancellationError() }
              try w.writeAllBytes(chunk)
            }
          }
        default: break
      }
    }

    return pid
  }

  /// Convenience: launches the process with variadic arguments and immediately awaits the result.
  ///
  /// - Parameters:
  ///   - executablePath: The executable to run.
  ///   - withStdin: Optional standard input.
  ///   - arguments: Command-line arguments (variadic).
  ///   - env: Extra environment variables.
  ///   - cd: Optional working directory.
  ///   - captureOutput: Whether to capture stdout.
  /// - Returns: The ``Output`` produced by the child process.
  /// - Throws: Any error from ``launch(_:withStdin:args:env:cd:captureOutput:)-4r7v4`` or ``value()``.
  public func run(
    _ executablePath: String,
    withStdin: (any Stdinable)? = nil,
    args arguments: any Arguable...,
    env : [String : String] = [:],
    cd : FilePath? = nil,
    captureOutput: Bool = true
  ) async throws -> Output {
    return try await run(executablePath, withStdin: withStdin, args: arguments, env: env, cd: cd, captureOutput: captureOutput)
  }

  /// Launches the process with an array of arguments and immediately awaits the result.
  ///
  /// - Parameters:
  ///   - executablePath: The executable to run.
  ///   - withStdin: Optional standard input.
  ///   - arguments: Command-line arguments.
  ///   - env: Extra environment variables.
  ///   - cd: Optional working directory.
  ///   - captureOutput: Whether to capture stdout.
  /// - Returns: The ``Output`` produced by the child process.
  /// - Throws: Any error from ``launch(_:withStdin:args:env:cd:captureOutput:)-4r7v4`` or ``value()``.
  public func run(
    _ executablePath: String,
    withStdin: (any Stdinable)? = nil,
    args arguments: [any Arguable] = [],
    env : [String : String] = [:],
    cd : FilePath? = nil,
    captureOutput: Bool = true
  ) async throws -> Output {

    let _ = try launch(
      executablePath,
      withStdin: withStdin,
      args: arguments,
      env: env,
      cd: cd,
      captureOutput: captureOutput
    )

    return try await value()
  }

  /// Waits for all I/O tasks to complete and collects the process exit code and captured output.
  ///
  /// May only be called once per `DarwinProcess` instance.
  ///
  /// - Returns: An ``Output`` with the exit code, stdout bytes, and stderr string.
  /// - Throws: Any error from the reader, feeder, or error tasks, or from `waitpid(2)`.
  public func value() async throws -> Output {
    defer { posix_spawn_file_actions_destroy(&actions); actions = nil }

    if awaitingValue { fatalError("DarwinProcess requested value twice") }
    awaitingValue = true


    async let status: Int32 = waitForExit(pid: pid)
    async let _ = feederTask?.value
    async let stderr = errorTask!.value

    try await readerTask?.value
    let stdout = pendingOutput


    let res = try await Output(code: status, data: stdout, error: stderr)

    // Close read ends after drain
    try? stdoutR?.close()
    try? stderrR?.close()

    return res
  }

  // MARK: - Helpers

  /// Waits for the process with `pid` to exit and returns its normalised exit code.
  ///
  /// Signal-terminated processes return `128 + signo`.
  ///
  /// - Parameter pid: The child PID to wait for.
  /// - Returns: The exit code.
  /// - Throws: ``POSIXErrno`` if `waitpid(2)` fails.
  private func waitForExit(pid: pid_t) async throws -> Int32 {
    try await Task.detached {
      var status: Int32 = 0
      while true {
        let w = Darwin.waitpid(pid, &status, 0)
        if w == -1 {
          if errno == EINTR { continue }
          throw POSIXErrno(fn: "waitpid")
        }
        break
      }

      if WIFEXITED(status) { return WEXITSTATUS(status) }
      if WIFSIGNALED(status) { return 128 + WTERMSIG(status) }
      return status
    }.value
  }


  // MARK: - posix_spawn file actions wiring (Darwin Swift overlay)

  /// Adds a `dup2` action to `actions`, and optionally adds a `close` of the source fd in the child.
  ///
  /// - Parameters:
  ///   - actions: The `posix_spawn_file_actions_t` to modify.
  ///   - from: The source file descriptor number.
  ///   - to: The destination file descriptor number (e.g. `STDIN_FILENO`).
  ///   - closeSourceInChild: When `true`, also adds a `posix_spawn_file_actions_addclose` for `from`.
  /// - Throws: ``POSIXErrno`` if either system call fails.
  private func addDup2AndClose(
    _ actions: inout posix_spawn_file_actions_t?,
    from: Int32,
    to: Int32,
    closeSourceInChild: Bool
  ) throws {
    let rc = posix_spawn_file_actions_adddup2(&actions, from, to)
    if rc != 0 { throw POSIXErrno(rc, fn: "posix_spawn_file_actions_adddup2") }

    if closeSourceInChild {
      let rc2 = posix_spawn_file_actions_addclose(&actions, from)
      if rc2 != 0 { throw POSIXErrno(rc2, fn: "posix_spawn_file_actions_addclose") }
    }
  }

  /// Converts an array of Swift strings to a null-terminated C string array and passes it to `body`.
  ///
  /// Each string is `strdup`-ed; the duplicates are freed before this function returns.
  ///
  /// - Parameters:
  ///   - strings: The strings to convert.
  ///   - body: A closure that receives the null-terminated `[UnsafeMutablePointer<CChar>?]`.
  /// - Returns: The value returned by `body`.
  /// - Throws: Any error thrown by `body`.
  private func withCStringArray<R>(
    _ strings: [String],
    _ body: ([UnsafeMutablePointer<CChar>?]) throws -> R
  ) throws -> R {
    var cStrings: [UnsafeMutablePointer<CChar>?] = []
    cStrings.reserveCapacity(strings.count + 1)

    for s in strings {
      cStrings.append(strdup(s))
    }
    cStrings.append(nil)

    defer {
      for p in cStrings where p != nil { free(p) }
    }

    return try body(cStrings)
  }
}

// ===================================================================================================

/// Replaces the current process image with `x`, passing `a` as `argv`.
///
/// If `execvp(3)` returns, something went wrong; the function returns the `errno`
/// value rather than terminating.
///
/// - Parameters:
///   - x: The executable path or name.
///   - a: The full argument array (including `argv[0]`).
/// - Returns: A ``POSIXErrno`` describing the failure reason.
public func execvp(_ x : String, _ a : [String]) -> POSIXErrno {
  let az = a.map { $0.withCString { strdup($0) } } + [UnsafeMutablePointer<CChar>.init(bitPattern: 0)]
  Darwin.execvp(x, az )
  return POSIXErrno()
}

public extension FileDescriptor {
  /// Reads whatever bytes are currently available on the file descriptor without blocking.
  ///
  /// Returns an empty array if no bytes are available (`EAGAIN`/`EWOULDBLOCK`), or at
  /// end-of-file.
  ///
  /// - Returns: All bytes currently available.
  /// - Throws: `Errno` for any error other than `EAGAIN`/`EWOULDBLOCK`.
  func readAvailableBytes() throws(Errno) -> [UInt8] {
    var result: [UInt8] = []
    var buffer = [UInt8](repeating: 0, count: 4096)

    while true {
      do {
        let count = try buffer.withUnsafeMutableBytes { rawBuffer in
          try self.read(into: rawBuffer)
        }
        if count == 0 {
          // EOF
          break
        }
        result.append(contentsOf: buffer.prefix(count))
      } catch let error as Errno {
        if error == .wouldBlock {
          // No more data currently available
          break
        }
        throw error
      } catch {
        throw Errno.ioError
      }
    }
    return result
  }

  /// Blocks the current thread until at least one byte is available to read on this descriptor.
  ///
  /// Uses `poll(2)` with an infinite timeout and retries on `EINTR`.
  ///
  /// - Throws: `Errno` if `poll` returns an error.
  func waitUntilReadable() throws(Errno) {
    var pfd = pollfd(
      fd: Int32(self.rawValue),
      events: Int16(POLLIN),
      revents: 0
    )

    while true {
      let rc = poll(&pfd, 1, -1)   // -1 = wait forever
      if rc > 0 {
        return
      }

      if rc == -1 {
        if errno == EINTR {
          continue
        }
        throw Errno(rawValue: errno)
      }
    }
  }

  /// Sets the `O_NONBLOCK` flag on this file descriptor.
  ///
  /// - Throws: `Errno` if `fcntl(F_SETFL)` fails.
  func makeNonBlocking() throws(Errno) {
    let flags = fcntl(self.rawValue, F_GETFL)
    guard flags >= 0 else { throw Errno(rawValue: errno) }
    guard fcntl(self.rawValue, F_SETFL, flags | O_NONBLOCK) >= 0 else {
      throw Errno(rawValue: errno)
    }
  }
}
