
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2025

import Darwin

/// Returns the path to the current user's preferred shell.
///
/// Reads the `SHELL` environment variable; falls back to `_PATH_BSHELL` (`/bin/sh`)
/// if the variable is not set.
///
/// - Returns: The absolute path to the shell executable.
public func getShell() -> String {
  let tmpShell = Environment["SHELL"]
  return tmpShell ?? _PATH_BSHELL
}

/// A namespace for POSIX `sysconf(3)` wrappers that query system configuration limits.
public struct Sysconf {
  /// The maximum number of bytes that may be passed to `execve(2)` as arguments.
  public static var scArgMax : Int { return Darwin.sysconf(Darwin._SC_ARG_MAX) }

  /// The maximum number of supplemental groups a process may belong to.
  public static var scNgroupsMax : Int { return Darwin.sysconf(Darwin._SC_NGROUPS_MAX) }

  /// The total number of processors configured on the system.
  public static var scNprocessorsConf : Int { return Darwin.sysconf(Darwin._SC_NPROCESSORS_CONF) }

  /// The number of processors currently online (available for scheduling).
  public static var scNprocessorsOnln : Int { return Darwin.sysconf(Darwin._SC_NPROCESSORS_ONLN) }

  /// The maximum number of files a process may have open simultaneously.
  public static var scOpenMax : Int { return sysconf(_SC_OPEN_MAX) }

  /// The size of a virtual memory page in bytes.
  public static var scPagesize : Int { return sysconf(_SC_PAGESIZE) }

  /// The total number of pages of physical memory.
  ///
  /// - Note: On 32-bit systems the product of this value and ``scPagesize`` may overflow `Int`.
  public static var scPhysPages : Int { return Darwin.sysconf(Darwin._SC_PHYS_PAGES) }
}

/// A namespace for `sysctlbyname(3)` wrappers that read kernel state by name.
public struct Sysctl {
  /// Reads a null-terminated string value from the kernel via `sysctlbyname`.
  ///
  /// - Parameter name: The dotted MIB name (e.g. `"kern.hostname"`).
  /// - Returns: The string value associated with the named sysctl.
  /// - Throws: ``POSIXErrno`` if the sysctl call fails.
  public static func getString(_ name : String) throws(POSIXErrno) -> String {
    var s : Int = 0
    let (e , r ) : (POSIXErrno?, String?) = name.withCString { (nm : UnsafePointer<Int8>) -> (POSIXErrno?, String? ) in
      if Darwin.sysctlbyname(nm, nil, &s, nil, 0) == -1 {
        return (POSIXErrno(errno, fn: "sysctl: \(name)"), nil)
      }
      return withUnsafeTemporaryAllocation(byteCount: s, alignment: 1) { b in
        if sysctlbyname(nm, b.baseAddress, &s, nil, 0) == -1 {
          return (POSIXErrno(errno, fn: "sysctl: \(name)"), nil)
        }
        let k = b.baseAddress?.assumingMemoryBound(to: UInt8.self)
        return (nil, String(cString: k!))
      }
    }
    if let e { throw e }
    else { return r! }
  }

  /// Reads a fixed-size value of type `T` from the kernel via `sysctlbyname`.
  ///
  /// - Parameter name: The dotted MIB name.
  /// - Returns: The value loaded from the sysctl buffer, interpreted as `T`.
  /// - Throws: ``POSIXErrno`` if the sysctl call fails.
  public static func get<T>(_ name : String) throws(POSIXErrno) -> T {
    var s : Int = 0
    let (e , r ) : (POSIXErrno?, T?) = name.withCString { nm in
      return withUnsafeTemporaryAllocation(byteCount: MemoryLayout<T>.size, alignment: 16 ) { b in
        if sysctlbyname(nm, b.baseAddress, &s, nil, 0) == -1 {
          return (POSIXErrno(errno, fn: "sysctl: \(name)"), nil)
        }
        let k = b.load(as: T.self)
        return (nil, k)
      }
    }
    if let e { throw e }
    else { return r! }
  }

  /// Reads an array of fixed-size values of type `T` from the kernel via `sysctlbyname`.
  ///
  /// - Parameter name: The dotted MIB name.
  /// - Returns: An array of values loaded from the sysctl buffer, interpreted as `[T]`.
  /// - Throws: ``POSIXErrno`` if the sysctl call fails.
  public static func getArray<T>(_ name : String) throws(POSIXErrno) -> [T] {
    var s : Int = 0
    let (e , r ) = name.withCString { nm -> (POSIXErrno?, [T]?) in
      if Darwin.sysctlbyname(nm, nil, &s, nil, 0) == -1 {
        return (POSIXErrno(errno, fn: "sysctl: \(name)"), nil)
      }
      return withUnsafeTemporaryAllocation(byteCount: s, alignment: 16) { b in
        if sysctlbyname(nm, b.baseAddress, &s, nil, 0) == -1 {
          return (POSIXErrno(errno, fn: "sysctl: \(name)"), nil)
        }
        let k = b.load(as: [T].self)
        return (nil, k)
      }
    }
    if let e { throw e }
    else { return r! }
  }
}
