
// Generated by Robert "r0ml" Lefkowitz <code@liberally.net> in 2026

import Darwin

/// A Swift representation of a POSIX `passwd` entry.
public struct Passwd {
  /// The login name of the user.
  public var name : String
  /// The numeric user ID.
  public var userId : Int
  /// The numeric primary group ID.
  public var groupId : Int
  /// The path to the user's home directory.
  public var home : String
  /// The path to the user's login shell.
  public var shell : String
  /// The user's full name (GECOS field).
  public var fullname : String
}

/// Looks up the `passwd` entry for the given username using `getpwnam_r(3)`.
///
/// - Parameter username: The login name to look up.
/// - Returns: A ``Passwd`` struct if the user exists, or `nil` if not found.
public func getPasswd(for username: String) -> Passwd? {
  return username.withPlatformString { cUsername -> Passwd? in
    var pwd = passwd()
    var result: UnsafeMutablePointer<passwd>? = nil
    let bufSize = sysconf(_SC_GETPW_R_SIZE_MAX)
    let buffer = UnsafeMutablePointer<Int8>.allocate(capacity: Int(bufSize))
    defer { buffer.deallocate() }

    let error = getpwnam_r(cUsername, &pwd, buffer, bufSize, &result)
    guard error == 0, result != nil else {
      return nil
    }

    let p = Passwd(name: String(cString: pwd.pw_name),
                   userId: Int(pwd.pw_uid),
                   groupId: Int(pwd.pw_gid),
                   home: String(cString: pwd.pw_dir),
                   shell: String(cString: pwd.pw_shell),
                   fullname: String(cString: pwd.pw_gecos),
    )
    return p
  }
}

/// Looks up the `passwd` entry for the given numeric user ID using `getpwuid_r(3)`.
///
/// - Parameter userid: The numeric UID to look up.
/// - Returns: A ``Passwd`` struct if the user exists, or `nil` if not found.
public func getPasswd(of userid: Int) -> Passwd? {
  var pwd = passwd()
  var result: UnsafeMutablePointer<passwd>? = nil
  let bufSize = sysconf(_SC_GETPW_R_SIZE_MAX)
  let buffer = UnsafeMutablePointer<Int8>.allocate(capacity: Int(bufSize))
  defer { buffer.deallocate() }

  let error = getpwuid_r(uid_t(userid), &pwd, buffer, bufSize, &result)
  guard error == 0, result != nil else {
    return nil
  }

  let p = Passwd(name: String(cString: pwd.pw_name),
                 userId: Int(pwd.pw_uid),
                 groupId: Int(pwd.pw_gid),
                 home: String(cString: pwd.pw_dir),
                 shell: String(cString: pwd.pw_shell),
                 fullname: String(cString: pwd.pw_gecos),
  )
  return p
}

/// The real user ID of the calling process.
public var userId : Int { Int(getuid()) }

/// The login name of the calling process's user.
public var userName : String { String(cString: getlogin()) }

/// The real group ID of the calling process.
public var groupId : Int { Int(getgid()) }

/// The effective user ID of the calling process.
public var effectiveUserId : Int { Int(geteuid()) }

/// The effective group ID of the calling process.
public var effectiveGroupId : Int { Int(getegid()) }

/// A Swift representation of a POSIX `group` entry.
public struct GroupEntry {
  /// The name of the group.
  public var name : String
  /// The numeric group ID.
  public var groupId : Int
  /// The login names of the group's members.
  public var members : [String]
}

/// Looks up the `group` entry for the given numeric group ID using `getgrgid_r(3)`.
///
/// - Parameter groupId: The numeric GID to look up.
/// - Returns: A ``GroupEntry`` struct if the group exists, or `nil` if not found.
public func getGroupEntry(of groupId: Int) -> GroupEntry? {
  var gr = group()
  var result: UnsafeMutablePointer<group>? = nil
  let bufSize = sysconf(_SC_GETGR_R_SIZE_MAX)
  let buffer = UnsafeMutablePointer<Int8>.allocate(capacity: Int(bufSize))
  defer { buffer.deallocate() }

  let error = getgrgid_r(gid_t(groupId), &gr, buffer, bufSize, &result)
  guard error == 0, result != nil else {
    return nil
  }

  var members: [String] = []
  var memberPtr = gr.gr_mem

  while let ptr = memberPtr?.pointee {
    members.append(String(cString: ptr))
    memberPtr = memberPtr?.advanced(by: 1)
  }

  let p = GroupEntry(name: String(cString: gr.gr_name),
                     groupId: Int(gr.gr_gid),
                     members: members
  )
  return p
}

/// Looks up the `group` entry for the given group name using `getgrnam_r(3)`.
///
/// - Parameter groupname: The group name to look up.
/// - Returns: A ``GroupEntry`` struct if the group exists, or `nil` if not found.
public func getGroupEntry(for groupname: String) -> GroupEntry? {
  return groupname.withPlatformString { cGroupname -> GroupEntry? in
    var gr = group()
    var result: UnsafeMutablePointer<group>? = nil
    let bufSize = sysconf(_SC_GETGR_R_SIZE_MAX)
    let buffer = UnsafeMutablePointer<Int8>.allocate(capacity: Int(bufSize))
    defer { buffer.deallocate() }

    let error = getgrnam_r(cGroupname, &gr, buffer, bufSize, &result)
    guard error == 0, result != nil else {
      return nil
    }

    var members: [String] = []
    var memberPtr = gr.gr_mem

    while let ptr = memberPtr?.pointee {
      members.append(String(cString: ptr))
      memberPtr = memberPtr?.advanced(by: 1)
    }

    let p = GroupEntry(name: String(cString: gr.gr_name),
                       groupId: Int(gr.gr_gid),
                       members: members
    )
    return p
  }
}
