// Copyright (c) 1868 Charles Babbage
// Modernized by Robert "r0ml" Lefkowitz <r0ml@liberally.net> in 2026

import Darwin

public struct Passwd {
  public var name : String
  public var userId : Int
  public var groupId : Int
  public var home : String
  public var shell : String
  public var fullname : String
}
/**
 Retrieve passwd data for provided username.  Generated by ChatGPT
 */
public func getPasswd(for username: String) -> Passwd? {
  // Convert Swift string to C string
  return username.withPlatformString { cUsername -> Passwd? in
    var pwd = passwd()
    var result: UnsafeMutablePointer<passwd>? = nil
    let bufSize = sysconf(_SC_GETPW_R_SIZE_MAX)
    let buffer = UnsafeMutablePointer<Int8>.allocate(capacity: Int(bufSize))
    defer { buffer.deallocate() }

    let error = getpwnam_r(cUsername, &pwd, buffer, bufSize, &result)
    guard error == 0, result != nil else {
      return nil // user not found
    }

    let p = Passwd(name: String(cString: pwd.pw_name),
                   userId: Int(pwd.pw_uid),
                   groupId: Int(pwd.pw_gid),
                   home: String(cString: pwd.pw_dir),
                   shell: String(cString: pwd.pw_shell),
                   fullname: String(cString: pwd.pw_gecos),
    )
    return p
  }
}

/**
 Retrieve passwd data for provided userid.  Generated by ChatGPT
 */
public func getPasswd(of userid: Int) -> Passwd? {
  // Convert Swift string to C string
  var pwd = passwd()
  var result: UnsafeMutablePointer<passwd>? = nil
  let bufSize = sysconf(_SC_GETPW_R_SIZE_MAX)
  let buffer = UnsafeMutablePointer<Int8>.allocate(capacity: Int(bufSize))
  defer { buffer.deallocate() }

  let error = getpwuid_r(uid_t(userid), &pwd, buffer, bufSize, &result)
  guard error == 0, result != nil else {
    return nil // user not found
  }

  let p = Passwd(name: String(cString: pwd.pw_name),
                 userId: Int(pwd.pw_uid),
                 groupId: Int(pwd.pw_gid),
                 home: String(cString: pwd.pw_dir),
                 shell: String(cString: pwd.pw_shell),
                 fullname: String(cString: pwd.pw_gecos),
  )
  return p
}

public var userId : Int { Int(getuid()) }
public var userName : String { String(cString: getlogin()) }
public var groupId : Int { Int(getgid()) }
public var effectiveUserId : Int { Int(geteuid()) }
public var effectiveGroupId : Int { Int(getegid()) }

public struct GroupEntry {
  public var name : String
  public var groupId : Int
  public var members : [String]
}

public func getGroupEntry(of groupId: Int) -> GroupEntry? {
  // Convert Swift string to C string
  var gr = group()
  var result: UnsafeMutablePointer<group>? = nil
  let bufSize = sysconf(_SC_GETGR_R_SIZE_MAX)
  let buffer = UnsafeMutablePointer<Int8>.allocate(capacity: Int(bufSize))
  defer { buffer.deallocate() }

  let error = getgrgid_r(gid_t(groupId), &gr, buffer, bufSize, &result)
  guard error == 0, result != nil else {
    return nil // user not found
  }

  var members: [String] = []
  var memberPtr = gr.gr_mem

  while let ptr = memberPtr?.pointee {
    members.append(String(cString: ptr))
    memberPtr = memberPtr?.advanced(by: 1)
  }

  let p = GroupEntry(name: String(cString: gr.gr_name),
                     groupId: Int(gr.gr_gid),
                     members: members
  )
  return p
}

public func getGroupEntry(for groupname: String) -> GroupEntry? {
  // Convert Swift string to C string
  return groupname.withPlatformString { cGroupname -> GroupEntry? in
    var gr = group()
    var result: UnsafeMutablePointer<group>? = nil
    let bufSize = sysconf(_SC_GETGR_R_SIZE_MAX)
    let buffer = UnsafeMutablePointer<Int8>.allocate(capacity: Int(bufSize))
    defer { buffer.deallocate() }

    let error = getgrnam_r(cGroupname, &gr, buffer, bufSize, &result)
    guard error == 0, result != nil else {
      return nil // group not found
    }

    var members: [String] = []
    var memberPtr = gr.gr_mem

    while let ptr = memberPtr?.pointee {
      members.append(String(cString: ptr))
      memberPtr = memberPtr?.advanced(by: 1)
    }

    let p = GroupEntry(name: String(cString: gr.gr_name),
                       groupId: Int(gr.gr_gid),
                       members: members
    )
    return p
  }
}
